import { Theme } from "@/src/context/themeContext";
import { StyleSheet } from "react-native";

export const createStyles = (theme: Theme) =>
	StyleSheet.create({
		goalPlanRow: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			marginTop: 10,
			gap: 8,
		},
		goalPlanText: {
			flex: 1,
			fontSize: 12,
			color: theme.textSecondary,
		},
		goalPaceBadge: {
			paddingHorizontal: 8,
			paddingVertical: 2,
			borderRadius: 10,
		},
		goalPaceText: {
			fontSize: 11,
			fontWeight: "700",
		},
		goalPlanPreview: {
			fontSize: 13,
			color: theme.primary,
			marginTop: 8,
			fontWeight: "600",
		},
		goalPlanCard: {
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 12,
			marginTop: 12,
		},
		goalPlanCardHeader: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
		},
		goalPlanValue: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
		},
		goalPlanHint: {
			fontSize: 12,
			color: theme.textSecondary,
			marginTop: 8,
		},
		clearLink: {
			fontSize: 12,
			color: theme.error,
			marginTop: 6,
		},
		priorityRow: {
			flexDirection: "row",
			gap: 8,
		},
		priorityChip: {
			flex: 1,
			alignItems: "center",
			paddingVertical: 8,
			borderRadius: 10,
			borderWidth: 1,
			borderColor: theme.border,
		},
		container: {
			flex: 1,
			backgroundColor: theme.background,
		},
		tabBar: {
			flexDirection: "row",
			paddingHorizontal: 16,
			paddingVertical: 12,
			backgroundColor: theme.surface,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
		},
		tab: {
			flex: 1,
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			gap: 4,
			paddingVertical: 8,
			borderRadius: 8,
		},
		tabActive: {
			backgroundColor: theme.primary + "15",
		},
		tabText: {
			fontSize: 12,
			fontWeight: "500",
			color: theme.textMuted,
		},
		tabTextActive: {
			color: theme.primary,
		},
		tabContent: {
			flex: 1,
			padding: 16,
		},
		overviewCard: {
			backgroundColor: theme.surface,
			borderRadius: 14,
			padding: 16,
			marginBottom: 20,
		},
		overviewRow: {
			flexDirection: "row",
			justifyContent: "space-between",
		},
		overviewStatCompact: {
			flex: 1,
			alignItems: "center",
		},
		overviewStatMiddle: {
			borderLeftWidth: 1,
			borderRightWidth: 1,
			borderColor: theme.border,
		},
		overviewLabelCompact: {
			fontSize: 11,
			color: theme.textMuted,
			fontWeight: "500",
			marginBottom: 4,
		},
		overviewValueCompact: {
			fontSize: 16,
			fontWeight: "700",
			color: theme.text,
		},
		overviewProgressCompact: {
			flexDirection: "row",
			alignItems: "center",
			gap: 10,
			marginTop: 14,
			paddingTop: 14,
			borderTopWidth: 1,
			borderTopColor: theme.border,
		},
		overviewProgressBg: {
			flex: 1,
			height: 6,
			backgroundColor: theme.border,
			borderRadius: 3,
			overflow: "hidden",
		},
		overviewProgressBar: {
			height: 6,
			borderRadius: 3,
			maxWidth: "100%",
		},
		overviewProgressText: {
			fontSize: 12,
			fontWeight: "600",
			width: 35,
		},
		sectionHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "flex-start",
			marginBottom: 16,
		},
		sectionTitle: {
			fontSize: 18,
			fontWeight: "700",
			color: theme.text,
		},
		sectionSubtitle: {
			fontSize: 13,
			color: theme.textMuted,
			marginTop: 2,
		},
		addSmallButton: {
			flexDirection: "row",
			alignItems: "center",
			gap: 6,
			backgroundColor: theme.primary,
			paddingVertical: 8,
			paddingHorizontal: 14,
			borderRadius: 10,
		},
		addSmallText: {
			fontSize: 13,
			fontWeight: "600",
			color: "#FFF",
		},
		emptyState: {
			alignItems: "center",
			paddingVertical: 40,
		},
		emptyText: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.text,
			marginTop: 12,
		},
		emptySubtext: {
			fontSize: 13,
			color: theme.textMuted,
			marginTop: 4,
		},
		budgetItem: {
			backgroundColor: theme.surface,
			borderRadius: 14,
			padding: 16,
			marginBottom: 10,
		},
		budgetHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			marginBottom: 12,
		},
		budgetCategory: {
			flexDirection: "row",
			alignItems: "center",
			gap: 12,
		},
		budgetIcon: {
			width: 40,
			height: 40,
			borderRadius: 10,
			justifyContent: "center",
			alignItems: "center",
		},
		budgetName: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
		},
		budgetLimit: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 2,
		},
		budgetProgressContainer: {
			flexDirection: "row",
			alignItems: "center",
			gap: 10,
		},
		budgetProgressBg: {
			flex: 1,
			height: 6,
			backgroundColor: theme.border,
			borderRadius: 3,
			overflow: "hidden",
		},
		budgetProgressFill: {
			height: "100%",
			borderRadius: 3,
		},
		budgetPercentage: {
			fontSize: 13,
			fontWeight: "600",
			width: 45,
			textAlign: "right",
		},
		savingsItem: {
			backgroundColor: theme.surface,
			borderRadius: 14,
			padding: 16,
			marginBottom: 10,
		},
		savingsHeader: {
			flexDirection: "row",
			alignItems: "center",
			marginBottom: 12,
		},
		savingsIcon: {
			width: 44,
			height: 44,
			borderRadius: 12,
			justifyContent: "center",
			alignItems: "center",
		},
		savingsInfo: {
			flex: 1,
			marginLeft: 12,
		},
		savingsName: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
		},
		savingsDeadline: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 2,
		},
		savingsAmounts: {
			alignItems: "flex-end",
		},
		savingsTarget: {
			fontSize: 16,
			fontWeight: "700",
			color: theme.text,
		},
		savingsCurrent: {
			fontSize: 11,
			color: theme.textMuted,
			marginTop: 2,
		},
		savingsProgressContainer: {
			flexDirection: "row",
			alignItems: "center",
			gap: 10,
		},
		savingsProgressBg: {
			flex: 1,
			height: 6,
			backgroundColor: theme.border,
			borderRadius: 3,
			overflow: "hidden",
		},
		savingsProgressFill: {
			height: "100%",
			borderRadius: 3,
		},
		savingsPercentage: {
			fontSize: 13,
			fontWeight: "600",
			width: 45,
			textAlign: "right",
		},
		billItem: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 14,
			padding: 14,
			marginBottom: 10,
		},
		billCheckbox: {
			width: 24,
			height: 24,
			borderRadius: 12,
			borderWidth: 2,
			borderColor: theme.border,
			justifyContent: "center",
			alignItems: "center",
		},
		billCheckboxChecked: {
			backgroundColor: theme.success,
			borderColor: theme.success,
		},
		billInfo: {
			flex: 1,
			marginLeft: 12,
		},
		billName: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
		},
		billNamePaid: {
			textDecorationLine: "line-through",
			color: theme.textMuted,
		},
		billMeta: {
			flexDirection: "row",
			alignItems: "center",
			gap: 8,
			marginTop: 4,
		},
		billDue: {
			fontSize: 12,
			color: theme.textMuted,
		},
		recurringBadge: {
			flexDirection: "row",
			alignItems: "center",
			gap: 3,
			paddingHorizontal: 6,
			paddingVertical: 2,
			backgroundColor: theme.primary + "15",
			borderRadius: 4,
		},
		recurringText: {
			fontSize: 10,
			color: theme.primary,
			fontWeight: "500",
		},
		billActions: {
			alignItems: "flex-end",
			gap: 8,
		},
		billAmount: {
			fontSize: 15,
			fontWeight: "700",
			color: theme.text,
		},
		debtSummary: {
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 24,
			alignItems: "center",
			marginBottom: 20,
		},
		debtSummaryTitle: {
			fontSize: 14,
			color: theme.textMuted,
			marginBottom: 8,
		},
		debtSummaryAmount: {
			fontSize: 32,
			fontWeight: "700",
			color: theme.error,
		},
		debtSummaryLabel: {
			fontSize: 13,
			color: theme.textMuted,
			marginTop: 4,
		},
		debtItem: {
			backgroundColor: theme.surface,
			borderRadius: 14,
			padding: 16,
			marginBottom: 10,
		},
		debtHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "flex-start",
			marginBottom: 12,
		},
		debtName: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
		},
		debtRate: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 2,
		},
		debtAmounts: {
			alignItems: "flex-end",
		},
		debtRemaining: {
			fontSize: 18,
			fontWeight: "700",
			color: theme.error,
		},
		debtOriginal: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 2,
		},
		debtProgressContainer: {
			flexDirection: "row",
			alignItems: "center",
			gap: 10,
			marginBottom: 12,
		},
		debtProgressBg: {
			flex: 1,
			height: 6,
			backgroundColor: theme.border,
			borderRadius: 3,
			overflow: "hidden",
		},
		debtProgressFill: {
			height: "100%",
			borderRadius: 3,
		},
		debtProgressText: {
			fontSize: 12,
			fontWeight: "500",
			color: theme.success,
			width: 55,
			textAlign: "right",
		},
		debtFooter: {
			flexDirection: "row",
			justifyContent: "space-between",
		},
		debtMinPayment: {
			fontSize: 12,
			color: theme.textMuted,
		},
		debtDue: {
			fontSize: 12,
			color: theme.textMuted,
		},
		modalOverlay: {
			flex: 1,
			backgroundColor: "rgba(0,0,0,0.5)",
			justifyContent: "flex-end",
		},
		modalContent: {
			backgroundColor: theme.background,
			borderTopLeftRadius: 24,
			borderTopRightRadius: 24,
			padding: 20,
			maxHeight: "80%",
		},
		modalHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			marginBottom: 20,
		},
		modalTitle: {
			fontSize: 18,
			fontWeight: "700",
			color: theme.text,
		},
		inputLabel: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.textSecondary,
			marginBottom: 8,
			marginTop: 12,
		},
		input: {
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 14,
			fontSize: 15,
			color: theme.text,
		},
		categoryScroll: {
			maxHeight: 48,
		},
		categoryOption: {
			flexDirection: "row",
			alignItems: "center",
			gap: 6,
			paddingVertical: 10,
			paddingHorizontal: 14,
			backgroundColor: theme.surface,
			borderRadius: 10,
			marginRight: 8,
			borderWidth: 1,
			borderColor: theme.border,
		},
		categoryOptionText: {
			fontSize: 12,
			color: theme.textMuted,
			fontWeight: "500",
		},
		checkboxRow: {
			flexDirection: "row",
			alignItems: "center",
			gap: 10,
			marginTop: 16,
		},
		checkbox: {
			width: 22,
			height: 22,
			borderRadius: 6,
			borderWidth: 2,
			borderColor: theme.border,
			justifyContent: "center",
			alignItems: "center",
		},
		checkboxChecked: {
			backgroundColor: theme.primary,
			borderColor: theme.primary,
		},
		checkboxLabel: {
			fontSize: 14,
			color: theme.text,
		},
		datePickerButton: {
			flexDirection: "row",
			alignItems: "center",
			gap: 12,
			backgroundColor: theme.surface,
			paddingVertical: 14,
			paddingHorizontal: 16,
			borderRadius: 12,
			borderWidth: 1,
			borderColor: theme.border,
			marginBottom: 16,
		},
		datePickerText: {
			fontSize: 15,
			color: theme.text,
			flex: 1,
		},
		submitButton: {
			backgroundColor: theme.primary,
			paddingVertical: 16,
			borderRadius: 12,
			alignItems: "center",
			marginTop: 20,
		},
		submitButtonText: {
			fontSize: 16,
			fontWeight: "600",
			color: "#FFF",
		},
		templateSection: {
			marginBottom: 24,
		},
		sectionLabel: {
			fontSize: 14,
			fontWeight: "700",
			color: theme.text,
			marginBottom: 16,
			letterSpacing: 0.2,
		},
		templateCard: {
			alignItems: "center",
			gap: 12,
			paddingHorizontal: 18,
			paddingVertical: 16,
			borderRadius: 18,
			borderWidth: 2.5,
			marginRight: 14,
			minWidth: 90,
			shadowColor: "#000",
			shadowOffset: { width: 0, height: 4 },
			shadowOpacity: 0.12,
			shadowRadius: 8,
			elevation: 4,
			position: "relative",
		},
		templateIconContainer: {
			width: 50,
			height: 50,
			borderRadius: 25,
			justifyContent: "center",
			alignItems: "center",
			shadowColor: "#000",
			shadowOffset: { width: 0, height: 2 },
			shadowOpacity: 0.1,
			shadowRadius: 4,
			elevation: 2,
		},
		templateCardText: {
			fontSize: 11,
			fontWeight: "700",
			textAlign: "center",
			letterSpacing: 0.3,
		},
		selectedBadge: {
			position: "absolute",
			top: 8,
			right: 8,
			backgroundColor: "rgba(255,255,255,0.3)",
			borderRadius: 12,
		},
		contributeGoalName: {
			fontSize: 20,
			fontWeight: "700",
			color: theme.text,
			textAlign: "center",
		},
		contributeProgress: {
			fontSize: 14,
			color: theme.textMuted,
			textAlign: "center",
			marginTop: 4,
		},
		deleteDebtButton: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			gap: 6,
			paddingVertical: 14,
			marginTop: 12,
		},
		deleteDebtText: {
			fontSize: 14,
			color: theme.error,
			fontWeight: "500",
		},
		// New styles for enhanced features
		savingsSummary: {
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 16,
			marginBottom: 20,
		},
		savingsSummaryRow: {
			flexDirection: "row",
			justifyContent: "space-between",
		},
		savingsSummaryItem: {
			flex: 1,
			alignItems: "center",
		},
		savingsSummaryLabel: {
			fontSize: 12,
			color: theme.textMuted,
			marginBottom: 4,
		},
		savingsSummaryValue: {
			fontSize: 18,
			fontWeight: "700",
			color: theme.text,
		},
		savingsItemCompleted: {
			opacity: 0.7,
			borderWidth: 1,
			borderColor: theme.success,
		},
		completedBadge: {
			flexDirection: "row",
			alignItems: "center",
			gap: 4,
			paddingHorizontal: 8,
			paddingVertical: 2,
			backgroundColor: theme.success + "20",
			borderRadius: 12,
		},
		completedBadgeText: {
			fontSize: 10,
			color: theme.success,
			fontWeight: "600",
		},
		billsSummary: {
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 16,
			marginBottom: 20,
		},
		billsSummaryRow: {
			flexDirection: "row",
			justifyContent: "space-between",
		},
		billsSummaryItem: {
			flex: 1,
			alignItems: "center",
		},
		billsSummaryLabel: {
			fontSize: 12,
			color: theme.textMuted,
			marginBottom: 4,
		},
		billsSummaryValue: {
			fontSize: 18,
			fontWeight: "700",
			color: theme.text,
		},
		billSectionLabel: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.textSecondary,
			marginBottom: 12,
		},
		billStatusIndicator: {
			width: 4,
			borderRadius: 2,
			alignSelf: "stretch",
			marginRight: 12,
		},
		billGradientOverlay: {
			...StyleSheet.absoluteFillObject,
			borderRadius: 12,
			pointerEvents: "none",
		},
		billItemPaid: {
			opacity: 0.6,
		},
		billEditRow: {
			flexDirection: "row",
			alignItems: "center",
			gap: 12,
		},
		showMoreText: {
			fontSize: 12,
			color: theme.textMuted,
			textAlign: "center",
			marginTop: 8,
		},
		debtSummaryRow: {
			flexDirection: "row",
			justifyContent: "space-between",
			width: "100%",
			marginBottom: 8,
		},
		debtSummaryItem: {
			flex: 1,
			alignItems: "center",
		},
		debtSummaryValue: {
			fontSize: 20,
			fontWeight: "700",
		},
		debtSummarySubLabel: {
			fontSize: 12,
			color: theme.textMuted,
		},
		debtItemLent: {
			borderLeftWidth: 3,
			borderLeftColor: theme.success,
		},
		debtItemSettled: {
			opacity: 0.6,
			backgroundColor: theme.surface + "80",
		},
		debtNameRow: {
			flexDirection: "row",
			alignItems: "center",
			gap: 8,
		},
		debtTypeBadge: {
			paddingHorizontal: 8,
			paddingVertical: 2,
			borderRadius: 10,
		},
		debtTypeText: {
			fontSize: 10,
			fontWeight: "600",
		},
		debtPaymentCount: {
			fontSize: 12,
			color: theme.textMuted,
		},
		deleteSettledButton: {
			position: "absolute",
			right: 10,
			bottom: 10,
			padding: 4,
		},
		debtTypeSelector: {
			flexDirection: "row",
			gap: 10,
			marginTop: 4,
		},
		debtTypeOption: {
			flex: 1,
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			gap: 6,
			paddingVertical: 12,
			borderRadius: 10,
			borderWidth: 1,
			borderColor: theme.border,
			backgroundColor: theme.surface,
		},
		debtTypeOptionText: {
			fontSize: 13,
			fontWeight: "500",
			color: theme.textMuted,
		},
		debtDetailHeader: {
			alignItems: "center",
			marginBottom: 8,
		},
		settledBadge: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			gap: 8,
			paddingVertical: 12,
			backgroundColor: theme.success + "15",
			borderRadius: 12,
			marginTop: 8,
		},
		settledText: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.success,
		},
		paymentHistory: {
			marginTop: 16,
			padding: 12,
			backgroundColor: theme.surface,
			borderRadius: 12,
		},
		paymentHistoryTitle: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.textSecondary,
			marginBottom: 10,
		},
		paymentHistoryItem: {
			flexDirection: "row",
			justifyContent: "space-between",
			paddingVertical: 6,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
		},
		paymentHistoryDate: {
			fontSize: 13,
			color: theme.textMuted,
		},
		paymentHistoryAmount: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.text,
		},
		accountSelector: {
			marginTop: 12,
		},
		accountSelectorLabel: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.textSecondary,
			marginBottom: 8,
		},
		accountOption: {
			paddingHorizontal: 14,
			paddingVertical: 10,
			borderRadius: 10,
			backgroundColor: theme.surface,
			borderWidth: 1,
			borderColor: theme.border,
			marginRight: 8,
			flexDirection: "row",
			alignItems: "center",
			gap: 6,
		},
		accountOptionSelected: {
			backgroundColor: theme.primary + "20",
			borderColor: theme.primary,
		},
		accountOptionText: {
			fontSize: 13,
			color: theme.textMuted,
		},
		accountOptionTextSelected: {
			color: theme.primary,
			fontWeight: "600",
		},
		billDueInfo: {
			fontSize: 13,
			color: theme.textMuted,
			textAlign: "center",
			marginTop: 4,
		},
		savingsActionsRow: {
			flexDirection: "row",
			justifyContent: "center",
			gap: 8,
			marginTop: 12,
		},
		savingsActionButton: {
			flexDirection: "row",
			alignItems: "center",
			gap: 4,
			paddingHorizontal: 12,
			paddingVertical: 6,
			borderRadius: 8,
		},
		savingsActionText: {
			fontSize: 12,
			fontWeight: "600",
		},
		accountSelectorContainer: {
			marginTop: 12,
		},
		accountScroll: {
			maxHeight: 100,
			gap: 8,
		},
		accountItem: {
			paddingHorizontal: 12,
			paddingVertical: 8,
			borderRadius: 10,
			backgroundColor: theme.surface,
			borderWidth: 1,
			borderColor: theme.border,
		},
		accountBalance: {
			fontSize: 11,
			color: theme.textMuted,
			marginTop: 2,
		},
		billItemOverdue: {
			borderWidth: 1,
			borderColor: theme.error,
		},
		billActionButtons: {
			flexDirection: "row",
			alignItems: "center",
			gap: 8,
		},
		billActionBtn: {
			padding: 6,
		},
		savingsDetailHeader: {
			alignItems: "center",
			marginBottom: 16,
		},
		savingsDetailProgress: {
			alignItems: "center",
			marginBottom: 16,
		},
		savingsDetailAmount: {
			fontSize: 28,
			fontWeight: "700",
			color: theme.text,
		},
		savingsDetailTarget: {
			fontSize: 14,
			color: theme.textMuted,
			marginBottom: 12,
		},
	});
