import { Theme } from "@/src/context/themeContext";
import { StyleSheet } from "react-native";

export const createStyles = (theme: Theme) =>
	StyleSheet.create({
		customRangeRow: {
			flexDirection: "row",
			gap: 8,
			marginTop: 10,
		},
		customRangeButton: {
			flex: 1,
			backgroundColor: theme.surface,
			borderRadius: 12,
			borderWidth: 1,
			borderColor: theme.border,
			paddingHorizontal: 12,
			paddingVertical: 8,
		},
		customRangeLabel: {
			fontSize: 11,
			color: theme.textMuted,
		},
		customRangeValueRow: {
			flexDirection: "row",
			alignItems: "center",
			gap: 6,
			marginTop: 2,
		},
		customRangeValue: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
		},
		sectionHint: {
			fontSize: 12,
			color: theme.textMuted,
		},
		healthTop: {
			flexDirection: "row",
			alignItems: "center",
			gap: 16,
		},
		healthScore: {
			fontSize: 26,
			fontWeight: "800",
		},
		healthSummary: {
			flex: 1,
		},
		healthLabel: {
			fontSize: 18,
			fontWeight: "700",
		},
		healthSub: {
			fontSize: 12,
			color: theme.textSecondary,
			marginTop: 4,
		},
		healthToggle: {
			fontSize: 12,
			color: theme.primary,
			fontWeight: "600",
			marginTop: 8,
		},
		factorRow: {
			marginTop: 14,
		},
		factorHeader: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			marginBottom: 6,
		},
		factorLabel: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.text,
		},
		factorScore: {
			fontSize: 13,
			fontWeight: "700",
		},
		factorBar: {
			height: 6,
			borderRadius: 3,
			backgroundColor: theme.surfaceLight,
			overflow: "hidden",
		},
		factorFill: {
			height: 6,
			borderRadius: 3,
		},
		projectedFill: {
			opacity: 0.3,
		},
		factorHint: {
			fontSize: 11,
			color: theme.textMuted,
			marginTop: 2,
			fontStyle: "italic",
		},
		factorDetail: {
			fontSize: 12,
			color: theme.textSecondary,
			marginTop: 4,
		},
		forecastLabel: {
			fontSize: 13,
			color: theme.textSecondary,
		},
		forecastValue: {
			fontSize: 30,
			fontWeight: "800",
			marginTop: 2,
		},
		forecastSub: {
			fontSize: 13,
			color: theme.textSecondary,
			marginTop: 2,
		},
		paceWrap: {
			marginTop: 14,
			marginBottom: 6,
		},
		paceMarker: {
			position: "absolute",
			top: 0,
			bottom: 0,
			width: 2,
			backgroundColor: theme.text,
		},
		forecastRow: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			paddingVertical: 6,
			gap: 12,
		},
		forecastRowLabel: {
			fontSize: 13,
			color: theme.textSecondary,
		},
		forecastRowValue: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
			flexShrink: 1,
			textAlign: "right",
		},
		forecastDivider: {
			height: 1,
			backgroundColor: theme.border,
			marginVertical: 6,
		},
		budgetRow: {
			paddingVertical: 10,
		},
		trendNet: {
			fontSize: 10,
			fontWeight: "600",
			marginTop: 2,
		},
		container: {
			flex: 1,
			backgroundColor: theme.background,
		},
		periodSection: {
			paddingHorizontal: 16,
			paddingVertical: 12,
			zIndex: 100,
		},
		filterControls: {
			flexDirection: "row",
			alignItems: "center",
			gap: 8,
		},
		periodDropdown: {
			flexDirection: "row",
			alignItems: "center",
			alignSelf: "flex-start",
			backgroundColor: theme.surface,
			paddingVertical: 10,
			paddingHorizontal: 16,
			borderRadius: 12,
			gap: 8,
		},
		accountFilterWrap: {
			flex: 1,
			position: "relative",
			zIndex: 2,
		},
		accountFilterButton: {
			minWidth: 0,
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			paddingVertical: 10,
			paddingHorizontal: 12,
			borderRadius: 12,
			gap: 7,
		},
		accountFilterLabel: {
			flex: 1,
		},
		accountDropdownMenu: {
			position: "absolute",
			top: 46,
			right: 0,
			minWidth: 180,
			maxWidth: 260,
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 4,
			shadowColor: "#000",
			shadowOffset: { width: 0, height: 4 },
			shadowOpacity: 0.15,
			shadowRadius: 12,
			elevation: 8,
			zIndex: 1000,
		},
		periodText: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
		},
		dropdownMenu: {
			position: "absolute",
			top: 54,
			left: 16,
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 4,
			shadowColor: "#000",
			shadowOffset: { width: 0, height: 4 },
			shadowOpacity: 0.15,
			shadowRadius: 12,
			elevation: 8,
			zIndex: 1000,
		},
		dropdownItem: {
			paddingVertical: 10,
			paddingHorizontal: 16,
			borderRadius: 8,
		},
		dropdownItemActive: {
			backgroundColor: theme.primary + "20",
		},
		dropdownItemText: {
			fontSize: 14,
			color: theme.text,
		},
		dropdownItemTextActive: {
			color: theme.primary,
			fontWeight: "600",
		},
		overviewCard: {
			marginHorizontal: 16,
			backgroundColor: theme.surface,
			borderRadius: 20,
			padding: 20,
		},
		overviewTop: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			marginBottom: 20,
		},
		progressRingContainer: {
			position: "relative",
			justifyContent: "center",
			alignItems: "center",
		},
		progressTextContainer: {
			position: "absolute",
			justifyContent: "center",
			alignItems: "center",
		},
		progressPercent: {
			fontSize: 22,
			fontWeight: "700",
		},
		progressLabel: {
			fontSize: 11,
			color: theme.textMuted,
			marginTop: -2,
		},
		overviewBalance: {
			flex: 1,
			alignItems: "flex-end",
			paddingRight: 8,
		},
		overviewBalanceLabel: {
			fontSize: 13,
			color: theme.textMuted,
			marginBottom: 4,
		},
		overviewBalanceValue: {
			fontSize: 24,
			fontWeight: "700",
		},
		overviewStats: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-around",
			paddingTop: 16,
			borderTopWidth: 1,
			borderTopColor: theme.border,
		},
		overviewStat: {
			flexDirection: "row",
			alignItems: "center",
			gap: 10,
		},
		overviewStatText: {},
		overviewDivider: {
			width: 1,
			height: 40,
			backgroundColor: theme.border,
		},
		overviewValue: {
			fontSize: 16,
			fontWeight: "700",
		},
		overviewLabel: {
			fontSize: 11,
			color: theme.textMuted,
			marginTop: 1,
		},
		quickStatsRow: {
			flexDirection: "row",
			marginHorizontal: 16,
			marginTop: 12,
			gap: 10,
		},
		quickStat: {
			flex: 1,
			backgroundColor: theme.surface,
			borderRadius: 14,
			padding: 12,
			flexDirection: "row",
			alignItems: "center",
			gap: 10,
		},
		quickStatIcon: {
			width: 36,
			height: 36,
			borderRadius: 10,
			justifyContent: "center",
			alignItems: "center",
		},
		quickStatContent: {
			flex: 1,
		},
		quickStatValue: {
			fontSize: 14,
			fontWeight: "700",
			color: theme.text,
		},
		quickStatLabel: {
			fontSize: 10,
			color: theme.textMuted,
		},
		comparisonCard: {
			marginHorizontal: 16,
			marginTop: 12,
			padding: 16,
			backgroundColor: theme.surface,
			borderRadius: 16,
		},
		comparisonHeader: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			marginBottom: 16,
		},
		comparisonTitle: {
			fontSize: 15,
			fontWeight: "700",
			color: theme.text,
		},
		comparisonSubtitle: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 3,
		},
		comparisonMetrics: {
			flexDirection: "row",
			gap: 12,
		},
		comparisonMetric: {
			flex: 1,
			minWidth: 0,
			padding: 12,
			backgroundColor: theme.background,
			borderRadius: 12,
		},
		comparisonLabel: {
			fontSize: 12,
			color: theme.textMuted,
		},
		comparisonAmount: {
			fontSize: 16,
			fontWeight: "700",
			color: theme.text,
			marginTop: 5,
		},
		comparisonChange: {
			fontSize: 12,
			fontWeight: "700",
			marginTop: 5,
		},
		comparisonPrevious: {
			fontWeight: "400",
			color: theme.textMuted,
		},
		section: {
			paddingHorizontal: 16,
			marginTop: 24,
		},
		sectionHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			marginBottom: 12,
		},
		sectionTitle: {
			fontSize: 17,
			fontWeight: "600",
			color: theme.text,
			marginBottom: 12,
		},
		categoryHeading: {
			marginBottom: 0,
		},
		categoryToggle: {
			paddingHorizontal: 8,
			paddingVertical: 5,
			marginBottom: 8,
		},
		categoryToggleText: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.primary,
		},
		legendRow: {
			flexDirection: "row",
			gap: 16,
		},
		legendItem: {
			flexDirection: "row",
			alignItems: "center",
			gap: 6,
		},
		legendDot: {
			width: 8,
			height: 8,
			borderRadius: 4,
		},
		legendText: {
			fontSize: 11,
			color: theme.textMuted,
		},
		emptyChart: {
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 40,
			alignItems: "center",
		},
		emptyChartText: {
			fontSize: 14,
			color: theme.textMuted,
			marginTop: 8,
		},
		chartCard: {
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 16,
		},
		trendsChart: {
			flexDirection: "row",
			alignItems: "flex-end",
			paddingVertical: 8,
			gap: 20,
			minWidth: "100%",
		},
		trendColumn: {
			alignItems: "center",
			width: 50,
		},
		trendBars: {
			flexDirection: "row",
			alignItems: "flex-end",
			gap: 4,
			height: 100,
		},
		trendBar: {
			width: 18,
			borderRadius: 4,
			minHeight: 4,
		},
		incomeBar: {
			backgroundColor: theme.success,
		},
		expenseBar: {
			backgroundColor: theme.error,
		},
		trendMonth: {
			fontSize: 11,
			color: theme.textMuted,
			marginTop: 8,
		},
		categoryCard: {
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 16,
		},
		categoryItem: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			paddingVertical: 10,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
		},
		categoryLeft: {
			flexDirection: "row",
			alignItems: "center",
			flex: 1,
		},
		categoryIcon: {
			width: 36,
			height: 36,
			borderRadius: 10,
			justifyContent: "center",
			alignItems: "center",
		},
		categoryInfo: {
			marginLeft: 12,
		},
		categoryName: {
			fontSize: 14,
			fontWeight: "500",
			color: theme.text,
		},
		categoryPercent: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 2,
		},
		categoryAmount: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
		},
		accountsCard: {
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 16,
		},
		accountItem: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			paddingVertical: 12,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
		},
		accountLeft: {
			flexDirection: "row",
			alignItems: "center",
			flex: 1,
		},
		accountIcon: {
			width: 40,
			height: 40,
			borderRadius: 12,
			justifyContent: "center",
			alignItems: "center",
		},
		accountInfo: {
			marginLeft: 12,
			flex: 1,
		},
		accountName: {
			fontSize: 14,
			fontWeight: "500",
			color: theme.text,
			marginBottom: 6,
		},
		accountBar: {
			height: 4,
			backgroundColor: theme.border,
			borderRadius: 2,
			overflow: "hidden",
		},
		accountBarFill: {
			height: "100%",
			borderRadius: 2,
		},
		accountBalance: {
			fontSize: 15,
			fontWeight: "600",
			marginLeft: 12,
		},
		tipsContainer: {
			gap: 10,
		},
		tipCard: {
			flexDirection: "row",
			alignItems: "flex-start",
			gap: 12,
			padding: 14,
			backgroundColor: theme.surface,
			borderRadius: 14,
			borderLeftWidth: 3,
		},
		tipContent: {
			flex: 1,
		},
		tipTitle: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
			marginBottom: 4,
		},
		tipText: {
			fontSize: 13,
			color: theme.textSecondary,
			lineHeight: 18,
		},
	});
