import { Theme } from "@/src/context/themeContext";
import { StyleSheet } from "react-native";

export const createStyles = (theme: Theme) =>
	StyleSheet.create({
		container: {
			flex: 1,
			backgroundColor: theme.background,
		},
		addFab: {
			position: "absolute",
			right: 20,
			bottom: 24,
			width: 56,
			height: 56,
			borderRadius: 28,
			backgroundColor: theme.primary,
			justifyContent: "center",
			alignItems: "center",
			// Raised above the list; the modals render above this anyway.
			elevation: 6,
			shadowColor: "#000",
			shadowOpacity: 0.3,
			shadowRadius: 6,
			shadowOffset: { width: 0, height: 3 },
		},
		searchContainer: {
			flexDirection: "row",
			paddingHorizontal: 16,
			paddingVertical: 12,
			gap: 10,
		},
		searchBar: {
			flex: 1,
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 12,
			paddingHorizontal: 12,
			gap: 8,
		},
		searchInput: {
			flex: 1,
			fontSize: 15,
			color: theme.text,
			paddingVertical: 12,
		},
		filterButton: {
			width: 48,
			height: 48,
			backgroundColor: theme.surface,
			borderRadius: 12,
			justifyContent: "center",
			alignItems: "center",
		},
		filterButtonActive: {
			backgroundColor: theme.primary,
		},
		filterSummary: {
			paddingHorizontal: 16,
			marginBottom: 4,
			fontSize: 12,
			color: theme.textMuted,
			fontWeight: "500",
		},
		popoverBackdrop: {
			flex: 1,
			backgroundColor: "rgba(0,0,0,0.25)",
		},
		popover: {
			position: "absolute",
			left: 16,
			right: 16,
			backgroundColor: theme.background,
			borderRadius: 16,
			padding: 16,
			borderWidth: 1,
			borderColor: theme.border,
			elevation: 10,
			shadowColor: "#000",
			shadowOpacity: 0.25,
			shadowRadius: 12,
			shadowOffset: { width: 0, height: 6 },
		},
		chipWrap: {
			flexDirection: "row",
			flexWrap: "wrap",
			gap: 8,
		},
		customRange: {
			flexDirection: "row",
			gap: 10,
			marginTop: 12,
		},
		dateField: {
			flex: 1,
			backgroundColor: theme.surface,
			borderRadius: 12,
			paddingVertical: 10,
			paddingHorizontal: 12,
			borderWidth: 1,
			borderColor: theme.border,
		},
		dateFieldLabel: {
			fontSize: 11,
			color: theme.textMuted,
			marginBottom: 2,
		},
		dateFieldValue: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
		},
		popoverFooter: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			marginTop: 14,
		},
		resetText: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.textMuted,
		},
		doneButton: {
			backgroundColor: theme.primary,
			paddingVertical: 8,
			paddingHorizontal: 22,
			borderRadius: 10,
		},
		doneButtonText: {
			color: "#FFF",
			fontSize: 14,
			fontWeight: "600",
		},
		quickFilter: {
			paddingVertical: 8,
			paddingHorizontal: 16,
			backgroundColor: theme.surface,
			borderRadius: 20,
		},
		quickFilterActive: {
			backgroundColor: theme.primary,
		},
		quickFilterText: {
			fontSize: 13,
			color: theme.textMuted,
			fontWeight: "500",
		},
		quickFilterTextActive: {
			color: "#FFF",
		},
		dateFilters: {
			flexDirection: "row",
			paddingHorizontal: 16,
			gap: 6,
			marginBottom: 8,
		},
		dateFilterOption: {
			paddingVertical: 6,
			paddingHorizontal: 12,
			borderRadius: 8,
		},
		dateFilterOptionActive: {
			backgroundColor: theme.primary + "20",
		},
		dateFilterText: {
			fontSize: 12,
			color: theme.textMuted,
			fontWeight: "500",
		},
		dateFilterTextActive: {
			color: theme.primary,
		},
		expandedFilters: {
			paddingHorizontal: 16,
			paddingVertical: 12,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
		},
		filterLabel: {
			fontSize: 12,
			fontWeight: "600",
			color: theme.textSecondary,
			marginBottom: 8,
		},
		categoryFilterOption: {
			flexDirection: "row",
			alignItems: "center",
			gap: 6,
			paddingVertical: 8,
			paddingHorizontal: 12,
			backgroundColor: theme.surface,
			borderRadius: 20,
			marginRight: 8,
			borderWidth: 1,
			borderColor: theme.border,
		},
		categoryFilterText: {
			fontSize: 12,
			color: theme.textMuted,
			fontWeight: "500",
		},
		listContent: {
			padding: 16,
			paddingBottom: 32,
		},
		dateGroup: {
			marginBottom: 20,
		},
		dateHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			marginBottom: 10,
		},
		dateText: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.textSecondary,
		},
		dateTotals: {
			flexDirection: "row",
			gap: 12,
		},
		dateTotal: {
			fontSize: 12,
			fontWeight: "600",
		},
		transactionItem: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			padding: 14,
			borderRadius: 14,
			marginBottom: 8,
			gap: 12,
		},
		transactionItemSelected: {
			borderWidth: 1,
			borderColor: theme.primary,
			backgroundColor: theme.primary + "15",
		},
		selectionCheckbox: {
			marginRight: -4,
		},
		selectionBar: {
			flexDirection: "row",
			alignItems: "center",
			gap: 12,
			paddingHorizontal: 16,
			paddingVertical: 10,
			backgroundColor: theme.surface,
		},
		selectionBarText: {
			flex: 1,
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
		},
		selectionBarButton: {
			padding: 4,
		},
		transactionIcon: {
			width: 44,
			height: 44,
			borderRadius: 12,
			justifyContent: "center",
			alignItems: "center",
		},
		transactionInfo: {
			flex: 1,
		},
		transactionDescription: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
			marginBottom: 2,
		},
		transactionMeta: {
			fontSize: 12,
			color: theme.textMuted,
			marginBottom: 2,
		},
		transactionBalance: {
			fontSize: 11,
			color: theme.textSecondary,
			fontWeight: "500",
		},
		transactionAmountContainer: {
			alignItems: "flex-end",
		},
		transactionAmount: {
			fontSize: 16,
			fontWeight: "700",
		},
		transactionTime: {
			fontSize: 11,
			color: theme.textMuted,
			marginTop: 2,
		},
		emptyState: {
			flex: 1,
			justifyContent: "center",
			alignItems: "center",
			paddingVertical: 60,
		},
		emptyIcon: {
			width: 100,
			height: 100,
			borderRadius: 50,
			backgroundColor: theme.surface,
			justifyContent: "center",
			alignItems: "center",
			marginBottom: 16,
		},
		emptyTitle: {
			fontSize: 18,
			fontWeight: "600",
			color: theme.text,
			marginBottom: 4,
		},
		emptySubtitle: {
			fontSize: 14,
			color: theme.textMuted,
			textAlign: "center",
		},
		modalOverlay: {
			flex: 1,
			backgroundColor: "rgba(0,0,0,0.5)",
			justifyContent: "flex-end",
		},
		modalContent: {
			backgroundColor: theme.background,
			borderTopLeftRadius: 24,
			borderTopRightRadius: 24,
			padding: 20,
		},
		modalHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			marginBottom: 20,
		},
		modalTitle: {
			fontSize: 18,
			fontWeight: "700",
			color: theme.text,
		},
		detailCard: {
			alignItems: "center",
			paddingVertical: 24,
			marginBottom: 20,
		},
		detailIcon: {
			width: 72,
			height: 72,
			borderRadius: 20,
			justifyContent: "center",
			alignItems: "center",
			marginBottom: 16,
		},
		detailAmount: {
			fontSize: 32,
			fontWeight: "700",
			marginBottom: 4,
		},
		detailDescription: {
			fontSize: 16,
			color: theme.textSecondary,
		},
		detailRows: {
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 4,
			marginBottom: 20,
		},
		detailRow: {
			flexDirection: "row",
			justifyContent: "space-between",
			paddingVertical: 12,
			paddingHorizontal: 16,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
		},
		detailLabel: {
			fontSize: 14,
			color: theme.textMuted,
		},
		detailValue: {
			fontSize: 14,
			fontWeight: "500",
			color: theme.text,
			textAlign: "right",
			flex: 1,
			marginLeft: 16,
		},
		modalActions: {
			flexDirection: "row",
			gap: 12,
		},
		editButton: {
			flex: 1,
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			gap: 8,
			backgroundColor: theme.primary + "20",
			paddingVertical: 14,
			borderRadius: 12,
		},
		editButtonText: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.primary,
		},
		deleteButton: {
			flex: 1,
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			gap: 8,
			backgroundColor: theme.error + "15",
			paddingVertical: 14,
			borderRadius: 12,
		},
		deleteButtonText: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.error,
		},
	});
