import { Theme } from "@/src/context/themeContext";
import { StyleSheet } from "react-native";

export const createStyles = (theme: Theme) =>
	StyleSheet.create({
		container: {
			flex: 1,
			backgroundColor: theme.background,
		},
		loadingContainer: {
			flex: 1,
			justifyContent: "center",
			alignItems: "center",
			backgroundColor: theme.background,
		},
		loadingText: {
			marginTop: 16,
			fontSize: 16,
			color: theme.textSecondary,
		},
		header: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			paddingHorizontal: 20,
			paddingTop: 16,
			paddingBottom: 12,
		},
		title: {
			fontSize: 28,
			fontWeight: "700",
			color: theme.text,
		},
		headerActions: {
			flexDirection: "row",
			alignItems: "center",
			gap: 12,
		},
		invitationBadge: {
			width: 44,
			height: 44,
			borderRadius: 22,
			backgroundColor: theme.primary,
			justifyContent: "center",
			alignItems: "center",
			position: "relative",
		},
		badge: {
			position: "absolute",
			top: -2,
			right: -2,
			backgroundColor: theme.error,
			borderRadius: 10,
			minWidth: 18,
			height: 18,
			justifyContent: "center",
			alignItems: "center",
			borderWidth: 2,
			borderColor: theme.background,
		},
		badgeText: {
			color: "#FFF",
			fontSize: 10,
			fontWeight: "700",
		},
		invitationsButton: {
			position: "relative",
			padding: 8,
		},
		invitationsBadge: {
			position: "absolute",
			top: 4,
			right: 4,
			backgroundColor: theme.error,
			borderRadius: 10,
			minWidth: 18,
			height: 18,
			justifyContent: "center",
			alignItems: "center",
		},
		invitationsBadgeText: {
			color: "#FFF",
			fontSize: 11,
			fontWeight: "600",
		},
		// Invitations Card
		invitationsCard: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.primary + "15",
			marginHorizontal: 16,
			marginBottom: 16,
			padding: 14,
			borderRadius: 14,
			borderWidth: 1,
			borderColor: theme.primary + "30",
		},
		invitationsIcon: {
			width: 44,
			height: 44,
			borderRadius: 12,
			backgroundColor: theme.primary + "20",
			justifyContent: "center",
			alignItems: "center",
		},
		invitationsContent: {
			flex: 1,
			marginLeft: 12,
		},
		invitationsTitle: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
		},
		invitationsSubtitle: {
			fontSize: 13,
			color: theme.textMuted,
			marginTop: 2,
		},
		// Group Cards
		groupCard: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 16,
		},
		groupCardHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "flex-start",
			marginBottom: 12,
		},
		groupInfo: {
			flex: 1,
		},
		groupName: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.text,
		},
		groupMeta: {
			fontSize: 13,
			color: theme.textMuted,
			marginTop: 2,
		},
		groupIcon: {
			width: 44,
			height: 44,
			borderRadius: 12,
			justifyContent: "center",
			alignItems: "center",
		},
		groupCardContent: {
			flexDirection: "row",
			justifyContent: "space-between",
			marginBottom: 12,
		},
		groupStat: {
			alignItems: "center",
		},
		groupStatValue: {
			fontSize: 16,
			fontWeight: "700",
			color: theme.text,
		},
		groupStatLabel: {
			fontSize: 11,
			color: theme.textMuted,
			marginTop: 2,
		},
		memberAvatars: {
			flexDirection: "row",
		},
		memberAvatarSmall: {
			width: 28,
			height: 28,
			borderRadius: 14,
			backgroundColor: theme.surfaceLight,
			justifyContent: "center",
			alignItems: "center",
			marginLeft: -8,
			borderWidth: 2,
			borderColor: theme.surface,
		},
		memberAvatarSmallFirst: {
			marginLeft: 0,
		},
		memberAvatarText: {
			fontSize: 10,
			fontWeight: "600",
			color: theme.textSecondary,
		},
		moreMembers: {
			backgroundColor: theme.textMuted,
		},
		moreMembersText: {
			color: "#FFF",
		},
		// Group List
		groupList: {
			gap: 12,
			paddingHorizontal: 16,
		},
		groupIconContainer: {
			width: 50,
			height: 50,
			borderRadius: 14,
			justifyContent: "center",
			alignItems: "center",
		},
		groupContent: {
			flex: 1,
			marginLeft: 14,
		},
		groupAmount: {
			flexDirection: "row",
			alignItems: "center",
			gap: 4,
		},
		groupTotal: {
			fontSize: 16,
			fontWeight: "700",
			color: theme.text,
		},
		// Empty State
		emptyState: {
			alignItems: "center",
			paddingVertical: 60,
		},
		emptyIcon: {
			width: 100,
			height: 100,
			borderRadius: 50,
			backgroundColor: theme.surface,
			justifyContent: "center",
			alignItems: "center",
			marginBottom: 16,
		},
		emptyContainer: {
			flex: 1,
			justifyContent: "center",
			alignItems: "center",
			padding: 40,
		},
		emptyTitle: {
			fontSize: 18,
			fontWeight: "600",
			color: theme.text,
		},
		emptySubtitle: {
			fontSize: 14,
			color: theme.textMuted,
			textAlign: "center",
			marginTop: 4,
			marginBottom: 20,
		},
		emptyText: {
			fontSize: 14,
			color: theme.textSecondary,
			textAlign: "center",
			marginBottom: 24,
		},
		emptyButton: {
			flexDirection: "row",
			alignItems: "center",
			gap: 6,
			backgroundColor: theme.primary,
			paddingVertical: 12,
			paddingHorizontal: 20,
			borderRadius: 12,
		},
		emptyButtonText: {
			color: "#FFF",
			fontWeight: "600",
			fontSize: 15,
		},
		// FAB
		createGroupButton: {
			position: "absolute",
			bottom: 24,
			right: 20,
			backgroundColor: theme.primary,
			width: 56,
			height: 56,
			borderRadius: 28,
			justifyContent: "center",
			alignItems: "center",
			shadowColor: theme.primary,
			shadowOffset: { width: 0, height: 4 },
			shadowOpacity: 0.3,
			shadowRadius: 8,
			elevation: 6,
		},
		// Detail View
		detailContainer: {
			flex: 1,
			backgroundColor: theme.background,
		},
		detailHeader: {
			flexDirection: "row",
			alignItems: "center",
			paddingHorizontal: 16,
			paddingTop: 8,
			paddingBottom: 12,
			gap: 12,
		},
		backButton: {
			padding: 4,
		},
		detailHeaderContent: {
			flex: 1,
		},
		detailTitle: {
			fontSize: 22,
			fontWeight: "700",
			color: theme.text,
		},
		detailSubtitle: {
			fontSize: 13,
			color: theme.textSecondary,
			marginTop: 2,
		},
		summaryCard: {
			flexDirection: "row",
			marginHorizontal: 16,
			borderRadius: 16,
			padding: 16,
			marginBottom: 16,
		},
		summaryItem: {
			flex: 1,
			alignItems: "center",
		},
		summaryValue: {
			fontSize: 20,
			fontWeight: "700",
		},
		summaryLabel: {
			fontSize: 12,
			color: theme.textSecondary,
			marginTop: 4,
		},
		summaryDivider: {
			width: 1,
			backgroundColor: theme.border,
			marginHorizontal: 8,
		},
		// Tabs
		tabBar: {
			flexDirection: "row",
			paddingHorizontal: 16,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
		},
		tab: {
			flex: 1,
			paddingVertical: 12,
			alignItems: "center",
		},
		tabActive: {
			borderBottomWidth: 2,
			borderBottomColor: theme.primary,
		},
		tabText: {
			fontSize: 14,
			fontWeight: "500",
			color: theme.textSecondary,
		},
		tabTextActive: {
			color: theme.primary,
		},
		detailContent: {
			flex: 1,
			paddingTop: 16,
		},
		section: {
			paddingHorizontal: 16,
			marginBottom: 20,
		},
		sectionTitle: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.text,
			marginBottom: 12,
		},
		// Debts
		debtCard: {
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 16,
			marginBottom: 10,
		},
		debtInfo: {
			flexDirection: "row",
			alignItems: "center",
			marginBottom: 12,
		},
		debtAvatar: {
			width: 36,
			height: 36,
			borderRadius: 18,
			backgroundColor: theme.error + "20",
			justifyContent: "center",
			alignItems: "center",
		},
		debtInitial: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.error,
		},
		debtFlow: {
			flex: 1,
			alignItems: "center",
			paddingHorizontal: 12,
		},
		debtFromName: {
			fontSize: 13,
			fontWeight: "500",
			color: theme.text,
		},
		debtArrow: {
			flexDirection: "row",
			alignItems: "center",
			gap: 6,
			marginVertical: 4,
		},
		debtOwes: {
			fontSize: 11,
			color: theme.textMuted,
		},
		debtAmountText: {
			fontSize: 14,
			fontWeight: "700",
			color: theme.primary,
		},
		debtToName: {
			fontSize: 13,
			fontWeight: "500",
			color: theme.text,
		},
		settleButton: {
			backgroundColor: theme.primary,
			paddingVertical: 8,
			borderRadius: 8,
			alignItems: "center",
		},
		settleButtonText: {
			color: "#FFF",
			fontWeight: "600",
			fontSize: 14,
		},
		allSettledCard: {
			backgroundColor: theme.success + "10",
			borderRadius: 12,
			padding: 24,
			alignItems: "center",
			marginHorizontal: 16,
		},
		allSettledTitle: {
			fontSize: 18,
			fontWeight: "600",
			color: theme.success,
			marginTop: 8,
		},
		allSettledText: {
			fontSize: 13,
			color: theme.textSecondary,
			marginTop: 4,
		},
		// Expenses
		expenseItem: {
			flexDirection: "row",
			alignItems: "center",
			paddingVertical: 10,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
		},
		expenseIconContainer: {
			width: 36,
			height: 36,
			borderRadius: 10,
			backgroundColor: theme.primary + "15",
			justifyContent: "center",
			alignItems: "center",
		},
		expenseContent: {
			flex: 1,
			marginLeft: 12,
		},
		expenseDesc: {
			fontSize: 14,
			fontWeight: "500",
			color: theme.text,
		},
		expenseMeta: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 2,
		},
		expenseAmountText: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
		},
		expenseCard: {
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 14,
			marginBottom: 10,
		},
		expenseCardHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
		},
		expenseCardLeft: {
			flexDirection: "row",
			alignItems: "center",
			flex: 1,
		},
		expenseCardTitle: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
		},
		expenseCardMeta: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 2,
		},
		expenseCardRight: {
			alignItems: "flex-end",
			// ensure there's room for the delete button positioned absolutely
			paddingRight: 44,
		},
		expenseCardAmount: {
			fontSize: 16,
			fontWeight: "700",
			color: theme.text,
		},
		expenseCardDate: {
			fontSize: 11,
			color: theme.textMuted,
			marginTop: 2,
		},
		expenseCardSplits: {
			marginTop: 12,
			paddingTop: 12,
			borderTopWidth: 1,
			borderTopColor: theme.border,
		},
		splitsTitle: {
			fontSize: 12,
			color: theme.textMuted,
			marginBottom: 8,
		},
		splitsList: {
			gap: 6,
		},
		splitItem: {
			flexDirection: "row",
			justifyContent: "space-between",
		},
		splitName: {
			fontSize: 13,
			color: theme.textSecondary,
		},
		splitAmount: {
			fontSize: 13,
			fontWeight: "500",
			color: theme.text,
		},
		deleteExpenseBtn: {
			position: "absolute",
			top: 10,
			right: 10,
			padding: 4,
		},
		emptySection: {
			alignItems: "center",
			padding: 30,
		},
		emptySectionText: {
			fontSize: 16,
			fontWeight: "500",
			color: theme.textSecondary,
			marginTop: 12,
		},
		emptySectionSubtext: {
			fontSize: 13,
			color: theme.textMuted,
			marginTop: 4,
		},
		// Settlements
		settlementItem: {
			flexDirection: "row",
			alignItems: "center",
			gap: 8,
			paddingVertical: 8,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
		},
		settlementText: {
			flex: 1,
			fontSize: 13,
			color: theme.textSecondary,
		},
		settlementDate: {
			fontSize: 11,
			color: theme.textMuted,
		},
		// Members
		memberCard: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 14,
			marginBottom: 8,
		},
		memberAvatar: {
			width: 44,
			height: 44,
			borderRadius: 22,
			backgroundColor: theme.surfaceLight,
			justifyContent: "center",
			alignItems: "center",
		},
		memberInitial: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.textSecondary,
		},
		memberInfo: {
			flex: 1,
			marginLeft: 12,
		},
		memberNameRow: {
			flexDirection: "row",
			alignItems: "center",
			gap: 6,
		},
		memberName: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
		},
		youBadge: {
			backgroundColor: theme.primary + "20",
			paddingHorizontal: 6,
			paddingVertical: 2,
			borderRadius: 4,
		},
		youBadgeText: {
			fontSize: 10,
			fontWeight: "600",
			color: theme.primary,
		},
		adminBadge: {
			backgroundColor: theme.warning + "20",
			paddingHorizontal: 6,
			paddingVertical: 2,
			borderRadius: 4,
		},
		adminBadgeText: {
			fontSize: 10,
			fontWeight: "600",
			color: theme.warning,
		},
		memberBalance: {
			fontSize: 13,
			marginTop: 2,
		},
		addMemberButtons: {
			flexDirection: "row",
			gap: 10,
			marginTop: 12,
		},
		addMemberButton: {
			flex: 1,
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			gap: 8,
			backgroundColor: theme.primary + "15",
			paddingVertical: 12,
			borderRadius: 10,
		},
		addMemberText: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.primary,
		},
		// FAB Container
		fabContainer: {
			position: "absolute",
			bottom: 20,
			left: 16,
			right: 16,
		},
		fab: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			gap: 8,
			paddingVertical: 14,
			borderRadius: 14,
			shadowColor: "#000",
			shadowOffset: { width: 0, height: 4 },
			shadowOpacity: 0.2,
			shadowRadius: 8,
			elevation: 5,
		},
		fabText: {
			color: "#FFF",
			fontSize: 16,
			fontWeight: "600",
		},
		// Modal Styles
		// Bottom-sheet variant, mirroring AddTransactionModal.
		sheetOverlay: {
			flex: 1,
			backgroundColor: "rgba(0,0,0,0.5)",
			justifyContent: "flex-end",
		},
		sheetContainer: {
			backgroundColor: theme.background,
			borderTopLeftRadius: 24,
			borderTopRightRadius: 24,
			maxHeight: "90%",
			paddingHorizontal: 20,
			paddingTop: 8,
			paddingBottom: 20,
		},
		sheetHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			paddingVertical: 14,
			marginBottom: 8,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
		},
		modalHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			paddingHorizontal: 16,
			paddingVertical: 12,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
		},
		modalCancel: {
			fontSize: 16,
			color: theme.textSecondary,
		},
		modalTitle: {
			fontSize: 17,
			fontWeight: "600",
			color: theme.text,
		},
		modalSave: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.primary,
		},
		// Form Styles
		formGroup: {
			marginBottom: 20,
		},
		formLabel: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
			marginBottom: 8,
		},
		formInput: {
			backgroundColor: theme.surface,
			borderRadius: 10,
			paddingHorizontal: 14,
			paddingVertical: 12,
			fontSize: 15,
			color: theme.text,
			borderWidth: 1,
			borderColor: theme.border,
		},
		// Type Grid
		typeGrid: {
			flexDirection: "row",
			flexWrap: "wrap",
			gap: 10,
		},
		typeOption: {
			width: "30%",
			alignItems: "center",
			paddingVertical: 14,
			borderRadius: 10,
			borderWidth: 1,
			borderColor: theme.border,
			backgroundColor: theme.surface,
		},
		typeLabel: {
			fontSize: 12,
			color: theme.textSecondary,
			marginTop: 6,
		},
		// Color Grid
		colorGrid: {
			flexDirection: "row",
			flexWrap: "wrap",
			gap: 12,
		},
		colorOption: {
			width: 40,
			height: 40,
			borderRadius: 20,
			justifyContent: "center",
			alignItems: "center",
		},
		colorOptionSelected: {
			borderWidth: 3,
			borderColor: "#FFF",
			shadowColor: "#000",
			shadowOffset: { width: 0, height: 2 },
			shadowOpacity: 0.3,
			shadowRadius: 4,
			elevation: 4,
		},
		// Alert Modal
		alertOverlay: {
			flex: 1,
			backgroundColor: "rgba(0,0,0,0.5)",
			justifyContent: "center",
			alignItems: "center",
			padding: 20,
		},
		alertContainer: {
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 24,
			width: "100%",
			maxWidth: 340,
		},
		alertTitle: {
			fontSize: 18,
			fontWeight: "600",
			color: theme.text,
			marginBottom: 8,
		},
		alertMessage: {
			fontSize: 14,
			color: theme.textSecondary,
			marginBottom: 16,
		},
		alertInput: {
			backgroundColor: theme.background,
			borderRadius: 10,
			paddingHorizontal: 14,
			paddingVertical: 12,
			fontSize: 15,
			color: theme.text,
			borderWidth: 1,
			borderColor: theme.border,
			marginBottom: 16,
		},
		alertButtons: {
			flexDirection: "row",
			gap: 10,
		},
		alertButtonCancel: {
			flex: 1,
			paddingVertical: 12,
			borderRadius: 10,
			backgroundColor: theme.surfaceLight,
			alignItems: "center",
		},
		alertButtonCancelText: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.textSecondary,
		},
		alertButtonConfirm: {
			flex: 1,
			paddingVertical: 12,
			borderRadius: 10,
			backgroundColor: theme.primary,
			alignItems: "center",
		},
		alertButtonConfirmText: {
			fontSize: 15,
			fontWeight: "600",
			color: "#FFF",
		},
		// Search
		searchContainer: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 10,
			paddingHorizontal: 12,
			marginBottom: 20,
			borderWidth: 1,
			borderColor: theme.border,
		},
		searchInput: {
			flex: 1,
			paddingVertical: 12,
			paddingHorizontal: 10,
			fontSize: 15,
			color: theme.text,
		},
		searchButton: {
			backgroundColor: theme.primary,
			paddingHorizontal: 16,
			paddingVertical: 8,
			borderRadius: 8,
		},
		searchButtonText: {
			color: "#FFF",
			fontSize: 14,
			fontWeight: "600",
		},
		searchResults: {
			gap: 10,
		},
		searchResultItem: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 12,
		},
		searchResultAvatar: {
			width: 44,
			height: 44,
			borderRadius: 22,
			backgroundColor: theme.primary + "20",
			justifyContent: "center",
			alignItems: "center",
		},
		searchResultInitial: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.primary,
		},
		searchResultInfo: {
			flex: 1,
			marginLeft: 12,
		},
		searchResultName: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
		},
		searchResultEmail: {
			fontSize: 13,
			color: theme.textSecondary,
			marginTop: 2,
		},
		inviteButton: {
			backgroundColor: theme.primary,
			paddingHorizontal: 16,
			paddingVertical: 8,
			borderRadius: 8,
		},
		inviteButtonText: {
			color: "#FFF",
			fontSize: 14,
			fontWeight: "600",
		},
		searchEmpty: {
			alignItems: "center",
			paddingVertical: 50,
		},
		searchEmptyText: {
			fontSize: 16,
			fontWeight: "500",
			color: theme.textSecondary,
			marginTop: 16,
		},
		searchEmptySubtext: {
			fontSize: 13,
			color: theme.textMuted,
			marginTop: 4,
		},
		// Amount Input
		amountInputContainer: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 10,
			borderWidth: 1,
			borderColor: theme.border,
		},
		currencyPrefix: {
			fontSize: 18,
			fontWeight: "600",
			color: theme.textSecondary,
			paddingLeft: 14,
		},
		amountInput: {
			flex: 1,
			paddingHorizontal: 8,
			paddingVertical: 14,
			fontSize: 18,
			fontWeight: "600",
			color: theme.text,
		},
		// Payer Selection
		payerOption: {
			alignItems: "center",
			marginRight: 14,
			paddingVertical: 8,
			paddingHorizontal: 12,
			borderRadius: 12,
			backgroundColor: theme.surface,
			borderWidth: 1,
			borderColor: theme.border,
		},
		payerOptionSelected: {
			backgroundColor: theme.primary + "15",
			borderColor: theme.primary,
		},
		payerAvatar: {
			width: 40,
			height: 40,
			borderRadius: 20,
			backgroundColor: theme.surfaceLight,
			justifyContent: "center",
			alignItems: "center",
			marginBottom: 6,
		},
		payerAvatarSelected: {
			backgroundColor: theme.primary + "30",
		},
		payerInitial: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.textSecondary,
		},
		payerInitialSelected: {
			color: theme.primary,
		},
		payerName: {
			fontSize: 12,
			color: theme.textSecondary,
		},
		payerNameSelected: {
			color: theme.primary,
			fontWeight: "600",
		},
		// Category Grid
		categoryGrid: {
			flexDirection: "row",
			flexWrap: "wrap",
			gap: 8,
		},
		categoryOption: {
			flexDirection: "row",
			alignItems: "center",
			paddingHorizontal: 12,
			paddingVertical: 10,
			borderRadius: 10,
			borderWidth: 1,
			borderColor: theme.border,
			backgroundColor: theme.surface,
			gap: 6,
		},
		categoryLabel: {
			fontSize: 13,
			color: theme.textSecondary,
		},
		// Split Type
		splitTypeRow: {
			flexDirection: "row",
			gap: 10,
		},
		splitTypeOption: {
			flex: 1,
			paddingVertical: 12,
			borderRadius: 10,
			backgroundColor: theme.surface,
			borderWidth: 1,
			borderColor: theme.border,
			alignItems: "center",
		},
		splitTypeOptionSelected: {
			backgroundColor: theme.primary + "15",
			borderColor: theme.primary,
		},
		splitTypeText: {
			fontSize: 14,
			color: theme.textSecondary,
		},
		splitTypeTextSelected: {
			color: theme.primary,
			fontWeight: "600",
		},
		// Split Preview
		splitPreview: {
			backgroundColor: theme.surface,
			borderRadius: 10,
			padding: 14,
			marginTop: 12,
		},
		splitPreviewTitle: {
			fontSize: 12,
			color: theme.textMuted,
			marginBottom: 10,
		},
		splitPreviewRow: {
			flexDirection: "row",
			justifyContent: "space-between",
			paddingVertical: 6,
		},
		splitPreviewName: {
			fontSize: 14,
			color: theme.textSecondary,
		},
		splitPreviewAmount: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
		},
		// Custom Splits
		customSplits: {
			marginTop: 12,
		},
		customSplitsTitle: {
			fontSize: 12,
			color: theme.textMuted,
			marginBottom: 10,
		},
		customSplitRow: {
			flexDirection: "row",
			alignItems: "center",
			marginBottom: 10,
		},
		customSplitName: {
			flex: 1,
			fontSize: 14,
			color: theme.text,
		},
		customSplitInput: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 8,
			borderWidth: 1,
			borderColor: theme.border,
			paddingHorizontal: 10,
			width: 120,
		},
		customSplitCurrency: {
			fontSize: 14,
			color: theme.textSecondary,
		},
		customSplitField: {
			flex: 1,
			paddingVertical: 10,
			paddingHorizontal: 6,
			fontSize: 14,
			color: theme.text,
			textAlign: "right",
		},
		// Member Select
		memberSelectList: {
			flexDirection: "row",
			flexWrap: "wrap",
			gap: 8,
		},
		memberSelectOption: {
			paddingHorizontal: 16,
			paddingVertical: 10,
			borderRadius: 10,
			backgroundColor: theme.surface,
			borderWidth: 1,
			borderColor: theme.border,
		},
		memberSelectOptionSelected: {
			backgroundColor: theme.primary + "15",
			borderColor: theme.primary,
		},
		memberSelectText: {
			fontSize: 14,
			color: theme.textSecondary,
		},
		memberSelectTextSelected: {
			color: theme.primary,
			fontWeight: "600",
		},
		// Invitations
		emptyInvitations: {
			alignItems: "center",
			paddingVertical: 50,
		},
		emptyInvitationsText: {
			fontSize: 16,
			color: theme.textSecondary,
			marginTop: 12,
		},
		invitationCard: {
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 16,
			marginBottom: 12,
		},
		invitationInfo: {
			marginBottom: 12,
		},
		invitationGroupName: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.text,
		},
		invitationInvitedBy: {
			fontSize: 13,
			color: theme.textSecondary,
			marginTop: 4,
		},
		invitationExpiry: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 2,
		},
		invitationActions: {
			flexDirection: "row",
			gap: 10,
		},
		declineButton: {
			flex: 1,
			paddingVertical: 10,
			borderRadius: 8,
			backgroundColor: theme.surfaceLight,
			alignItems: "center",
		},
		declineButtonText: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.textSecondary,
		},
		acceptButton: {
			flex: 1,
			paddingVertical: 10,
			borderRadius: 8,
			backgroundColor: theme.primary,
			alignItems: "center",
		},
		acceptButtonText: {
			fontSize: 14,
			fontWeight: "600",
			color: "#FFF",
		},
	});
