import { Theme } from "@/src/context/themeContext";
import { StyleSheet } from "react-native";

export const createStyles = (theme: Theme) =>
	StyleSheet.create({
		modalOverlay: {
			flex: 1,
			backgroundColor: "rgba(0,0,0,0.5)",
			justifyContent: "flex-end",
		},
		modalContent: {
			backgroundColor: theme.background,
			borderTopLeftRadius: 24,
			borderTopRightRadius: 24,
			paddingHorizontal: 20,
			paddingBottom: 34,
			maxHeight: "90%",
		},
		dragHandleContainer: {
			alignItems: "center",
			paddingVertical: 12,
		},
		dragHandle: {
			width: 40,
			height: 4,
			borderRadius: 2,
			backgroundColor: theme.border,
		},
		modalHeader: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			marginBottom: 20,
		},
		modalTitle: {
			fontSize: 20,
			fontWeight: "700",
			color: theme.text,
		},
		sectionLabel: {
			fontSize: 11,
			fontWeight: "700",
			color: theme.textMuted,
			letterSpacing: 1,
			marginTop: 20,
			marginBottom: 12,
		},
		inputGroup: {
			marginBottom: 20,
		},
		inputLabel: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.textSecondary,
			marginBottom: 8,
		},
		textInput: {
			backgroundColor: theme.surface,
			borderRadius: 12,
			paddingHorizontal: 16,
			paddingVertical: 14,
			fontSize: 16,
			color: theme.text,
			borderWidth: 1,
			borderColor: theme.border,
		},
		inputHint: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 6,
		},
		textArea: {
			minHeight: 80,
			textAlignVertical: "top",
		},
		colorGrid: {
			flexDirection: "row",
			flexWrap: "wrap",
			gap: 12,
		},
		colorOption: {
			width: 40,
			height: 40,
			borderRadius: 20,
			justifyContent: "center",
			alignItems: "center",
		},
		colorOptionSelected: {
			borderWidth: 3,
			borderColor: "#fff",
			shadowColor: "#000",
			shadowOffset: { width: 0, height: 2 },
			shadowOpacity: 0.3,
			shadowRadius: 4,
			elevation: 4,
		},
		iconSelector: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 12,
			paddingHorizontal: 16,
			paddingVertical: 12,
			borderWidth: 1,
			borderColor: theme.border,
		},
		selectedIcon: {
			width: 40,
			height: 40,
			borderRadius: 10,
			justifyContent: "center",
			alignItems: "center",
			marginRight: 12,
		},
		iconSelectorText: {
			flex: 1,
			fontSize: 15,
			color: theme.text,
		},
		iconGrid: {
			flexDirection: "row",
			flexWrap: "wrap",
			gap: 8,
			marginTop: 12,
			padding: 12,
			backgroundColor: theme.surface,
			borderRadius: 12,
		},
		iconOption: {
			width: 44,
			height: 44,
			borderRadius: 10,
			justifyContent: "center",
			alignItems: "center",
		},
		frequencyPickerContainer: {
			marginTop: 12,
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 12,
		},
		frequencyOptions: {
			gap: 8,
		},
		frequencyOptionEnhanced: {
			flexDirection: "row",
			alignItems: "center",
			padding: 12,
			borderRadius: 10,
			marginBottom: 8,
			borderWidth: 1,
			borderColor: theme.border,
		},
		frequencyOptionIconBox: {
			width: 36,
			height: 36,
			borderRadius: 8,
			justifyContent: "center",
			alignItems: "center",
			marginRight: 12,
		},
		frequencyOptionContent: {
			flex: 1,
		},
		frequencyOptionText: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
		},
		frequencyOptionDescription: {
			fontSize: 12,
			color: theme.textSecondary,
			marginTop: 2,
		},
		daysSelector: {
			marginTop: 12,
			padding: 12,
			backgroundColor: theme.surface,
			borderRadius: 10,
		},
		daysSelectorLabel: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.text,
			marginBottom: 10,
		},
		daysRow: {
			flexDirection: "row",
			justifyContent: "space-between",
		},
		dayButton: {
			width: 38,
			height: 38,
			borderRadius: 19,
			justifyContent: "center",
			alignItems: "center",
			borderWidth: 1,
			borderColor: theme.border,
		},
		dayButtonText: {
			fontSize: 12,
			fontWeight: "600",
			color: theme.textSecondary,
		},
		switchRow: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			backgroundColor: theme.surface,
			borderRadius: 12,
			paddingVertical: 12,
			paddingHorizontal: 16,
			borderWidth: 1,
			borderColor: theme.border,
			marginBottom: 16,
		},
		switchInfo: {
			flexDirection: "row",
			alignItems: "center",
			flex: 1,
		},
		switchTextContainer: {
			flex: 1,
		},
		switchTitle: {
			fontSize: 15,
			fontWeight: "500",
			color: theme.text,
		},
		switchSubtitle: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 2,
		},
		previewCard: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 16,
			borderWidth: 1,
			borderColor: theme.border,
		},
		previewIcon: {
			width: 50,
			height: 50,
			borderRadius: 14,
			justifyContent: "center",
			alignItems: "center",
			marginRight: 14,
		},
		previewInfo: {
			flex: 1,
		},
		previewName: {
			fontSize: 17,
			fontWeight: "600",
		},
		previewDescription: {
			fontSize: 13,
			color: theme.textMuted,
			marginTop: 2,
		},
		saveButton: {
			paddingVertical: 16,
			borderRadius: 12,
			alignItems: "center",
			marginTop: 10,
		},
		saveButtonText: {
			fontSize: 16,
			fontWeight: "700",
			color: "#fff",
		},
		typeOption: {
			flex: 1,
			padding: 16,
			borderRadius: 14,
			backgroundColor: theme.surfaceLight,
			borderWidth: 2,
			borderColor: theme.border,
			alignItems: "center",
		},
		typeOptionLabel: {
			marginTop: 8,
			fontWeight: "600",
			color: theme.text,
		},
		typeOptionHint: {
			fontSize: 11,
			color: theme.textMuted,
			marginTop: 2,
		},
		targetTypeOption: {
			flex: 1,
			paddingVertical: 12,
			borderRadius: 10,
			backgroundColor: theme.surfaceLight,
			borderWidth: 1,
			borderColor: theme.border,
			alignItems: "center",
		},
		targetTypeText: {
			fontSize: 13,
			fontWeight: "500",
			color: theme.textSecondary,
		},
		timePickerContainer: {
			backgroundColor: theme.surfaceLight,
			borderRadius: 14,
			marginTop: 12,
			overflow: "hidden",
		},
		timePickerDone: {
			padding: 14,
			alignItems: "center",
		},
	});
