import { Theme } from "@/src/context/themeContext";
import { StyleSheet } from "react-native";

export const createStyles = (theme: Theme) =>
	StyleSheet.create({
		container: {
			flex: 1,
			paddingHorizontal: 16,
		},
		greetingSection: {
			marginBottom: 20,
		},
		greeting: {
			fontSize: 24,
			fontWeight: "700",
			color: theme.text,
		},
		subGreeting: {
			fontSize: 14,
			color: theme.textMuted,
			marginTop: 4,
		},
		statsGrid: {
			flexDirection: "row",
			justifyContent: "space-between",
			marginBottom: 20,
		},
		statCard: {
			flex: 1,
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 10,
			alignItems: "center",
			marginHorizontal: 4,
			minWidth: 70,
		},
		statIcon: {
			width: 32,
			height: 32,
			borderRadius: 16,
			justifyContent: "center",
			alignItems: "center",
			marginBottom: 6,
		},
		statValue: {
			fontSize: 14,
			fontWeight: "700",
			color: theme.text,
			textAlign: "center",
		},
		statLabel: {
			fontSize: 9,
			color: theme.textMuted,
			marginTop: 2,
			textAlign: "center",
			flexShrink: 1,
		},
		activeWorkoutBanner: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.success,
			borderRadius: 16,
			padding: 16,
			marginBottom: 20,
		},
		activePulse: {
			width: 12,
			height: 12,
			borderRadius: 6,
			backgroundColor: "#FFFFFF",
			marginRight: 12,
		},
		activeWorkoutContent: {
			flex: 1,
		},
		activeWorkoutTitle: {
			fontSize: 16,
			fontWeight: "700",
			color: "#FFFFFF",
		},
		activeWorkoutSubtitle: {
			fontSize: 12,
			color: "#FFFFFF",
			opacity: 0.8,
		},
		section: {
			marginBottom: 24,
		},
		sectionHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			marginBottom: 12,
		},
		sectionTitle: {
			fontSize: 18,
			fontWeight: "700",
			color: theme.text,
			marginBottom: 12,
		},
		seeAll: {
			fontSize: 14,
			color: theme.primary,
			fontWeight: "600",
		},
		quickStartGrid: {
			flexDirection: "row",
			flexWrap: "wrap",
			gap: 12,
		},
		quickStartCard: {
			// Two per row at any width (fixed px went stale on rotation).
			flexGrow: 1,
			flexBasis: "40%",
			padding: 20,
			borderRadius: 16,
			alignItems: "center",
			gap: 8,
		},
		quickStartText: {
			fontSize: 13,
			fontWeight: "600",
			color: "#FFFFFF",
			flexShrink: 0,
		},
		activePlanCard: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 16,
		},
		planIcon: {
			width: 48,
			height: 48,
			borderRadius: 14,
			justifyContent: "center",
			alignItems: "center",
			marginRight: 12,
		},
		planContent: {
			flex: 1,
		},
		planName: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.text,
		},
		planMeta: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 2,
		},
		startPlanButton: {
			width: 40,
			height: 40,
			borderRadius: 20,
			backgroundColor: theme.primary,
			justifyContent: "center",
			alignItems: "center",
		},
		plansScroll: {
			marginLeft: -4,
		},
		planCard: {
			width: 140,
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 14,
			marginRight: 12,
			borderLeftWidth: 3,
		},
		planCardHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			marginBottom: 10,
		},
		planCardIcon: {
			width: 32,
			height: 32,
			borderRadius: 10,
			justifyContent: "center",
			alignItems: "center",
		},
		planCardDuration: {
			fontSize: 11,
			color: theme.textMuted,
		},
		planCardName: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
			marginBottom: 4,
		},
		planCardExercises: {
			fontSize: 11,
			color: theme.textMuted,
		},
		emptyCard: {
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 32,
			alignItems: "center",
			borderWidth: 2,
			borderColor: theme.border,
			borderStyle: "dashed",
		},
		emptyText: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.text,
			marginTop: 12,
		},
		emptySubtext: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 4,
		},
		emptyRecentCard: {
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 24,
			alignItems: "center",
		},
		emptyRecentText: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
			marginTop: 8,
		},
		emptyRecentSubtext: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 2,
		},
		recentCard: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 14,
			padding: 14,
			marginBottom: 10,
		},
		recentIcon: {
			width: 40,
			height: 40,
			borderRadius: 12,
			backgroundColor: theme.primary + "20",
			justifyContent: "center",
			alignItems: "center",
			marginRight: 12,
		},
		recentContent: {
			flex: 1,
		},
		recentName: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
		},
		recentMeta: {
			fontSize: 11,
			color: theme.textMuted,
			marginTop: 2,
		},
		recentVolume: {
			alignItems: "center",
		},
		recentVolumeValue: {
			fontSize: 16,
			fontWeight: "700",
			color: theme.primary,
		},
		recentVolumeLabel: {
			fontSize: 10,
			color: theme.textMuted,
		},
		tipCard: {
			flexDirection: "row",
			backgroundColor: theme.warning + "15",
			borderRadius: 16,
			padding: 16,
			gap: 12,
		},
		tipContent: {
			flex: 1,
		},
		tipTitle: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
			marginBottom: 4,
		},
		tipText: {
			fontSize: 12,
			color: theme.textSecondary,
			lineHeight: 18,
		},
		// Modal styles
		modalContainer: {
			flex: 1,
			backgroundColor: theme.background,
		},
		modalHeader: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			paddingHorizontal: 16,
			paddingVertical: 16,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
		},
		modalHeaderActions: {
			flexDirection: "row",
			alignItems: "center",
			gap: 16,
		},
		createExerciseBtn: {
			flexDirection: "row",
			alignItems: "center",
			gap: 4,
			paddingHorizontal: 14,
			paddingVertical: 6,
			backgroundColor: theme.primary + "20",
			borderRadius: 20,
			flexShrink: 0,
		},
		createExerciseBtnText: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.primary,
			flexShrink: 0,
		},
		saveButtonText: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.primary,
			flexShrink: 0,
		},
		modalTitle: {
			fontSize: 20,
			fontWeight: "700",
			color: theme.text,
			flexShrink: 0,
		},
		searchContainer: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 12,
			paddingHorizontal: 12,
			margin: 16,
			gap: 8,
		},
		searchInput: {
			flex: 1,
			paddingVertical: 12,
			fontSize: 16,
			color: theme.text,
		},
		muscleFilter: {
			paddingHorizontal: 16,
			marginBottom: 12,
			maxHeight: 44,
		},
		muscleChip: {
			paddingHorizontal: 14,
			paddingVertical: 8,
			borderRadius: 20,
			backgroundColor: theme.surface,
			marginRight: 8,
			alignItems: "center",
			justifyContent: "center",
			minHeight: 36,
			maxHeight: 36,
		},
		muscleChipActive: {
			backgroundColor: theme.primary,
		},
		muscleChipText: {
			fontSize: 13,
			color: theme.text,
			textAlign: "center",
		},
		muscleChipTextActive: {
			color: "#FFFFFF",
			fontWeight: "600",
		},
		exerciseList: {
			paddingHorizontal: 16,
			flexGrow: 1,
			paddingTop: 8,
		},
		exerciseItem: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 16,
			marginBottom: 10,
		},
		exerciseItemLeft: {
			flex: 1,
		},
		exerciseNameRow: {
			flexDirection: "row",
			alignItems: "center",
			gap: 8,
		},
		exerciseItemName: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.text,
		},
		customBadge: {
			backgroundColor: theme.primary + "20",
			paddingHorizontal: 8,
			paddingVertical: 2,
			borderRadius: 10,
		},
		customBadgeText: {
			fontSize: 10,
			fontWeight: "600",
			color: theme.primary,
		},
		exerciseItemMuscles: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 4,
			textTransform: "capitalize",
		},
		difficultyBadge: {
			paddingHorizontal: 10,
			paddingVertical: 4,
			borderRadius: 12,
		},
		difficultyText: {
			fontSize: 11,
			fontWeight: "600",
			textTransform: "capitalize",
		},
		emptyList: {
			alignItems: "center",
			paddingVertical: 40,
		},
		emptyListText: {
			fontSize: 16,
			color: theme.textMuted,
		},
		// Exercise Browser Modern Styles
		exerciseBrowserContainer: {
			flex: 1,
			backgroundColor: theme.background,
		},
		exerciseBrowserHeader: {
			backgroundColor: theme.surface,
			paddingBottom: 12,
			borderBottomLeftRadius: 24,
			borderBottomRightRadius: 24,
			shadowColor: "#000",
			shadowOffset: { width: 0, height: 2 },
			shadowOpacity: 0.1,
			shadowRadius: 8,
			elevation: 4,
		},
		exerciseBrowserHeaderTop: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			paddingHorizontal: 16,
			paddingTop: 12,
			paddingBottom: 16,
		},
		exerciseBrowserCloseBtn: {
			width: 40,
			height: 40,
			borderRadius: 20,
			backgroundColor: theme.background,
			alignItems: "center",
			justifyContent: "center",
		},
		exerciseBrowserTitle: {
			fontSize: 20,
			fontWeight: "700",
			color: theme.text,
		},
		exerciseBrowserCreateBtn: {
			width: 40,
			height: 40,
			alignItems: "center",
			justifyContent: "center",
		},
		exerciseSearchBar: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.background,
			marginHorizontal: 16,
			paddingHorizontal: 16,
			borderRadius: 16,
			gap: 12,
			height: 52,
		},
		exerciseSearchInput: {
			flex: 1,
			fontSize: 16,
			color: theme.text,
			paddingVertical: 12,
		},
		muscleGroupFilter: {
			marginTop: 16,
			maxHeight: 44,
		},
		muscleGroupFilterContent: {
			paddingHorizontal: 16,
			gap: 8,
		},
		muscleGroupChip: {
			flexDirection: "row",
			alignItems: "center",
			gap: 6,
			paddingHorizontal: 16,
			paddingVertical: 10,
			borderRadius: 24,
			backgroundColor: theme.background,
		},
		muscleGroupChipActive: {
			backgroundColor: theme.primary,
		},
		muscleGroupChipText: {
			fontSize: 14,
			fontWeight: "500",
			color: theme.text,
		},
		muscleGroupChipTextActive: {
			color: "#FFFFFF",
			fontWeight: "600",
		},
		categoryFilter: {
			marginTop: 8,
			maxHeight: 44,
		},
		categoryFilterContent: {
			paddingHorizontal: 16,
			gap: 8,
		},
		categoryChip: {
			paddingHorizontal: 14,
			paddingVertical: 9,
			borderRadius: 22,
			backgroundColor: theme.background,
		},
		categoryChipActive: {
			backgroundColor: theme.primary,
		},
		categoryChipText: {
			fontSize: 13,
			fontWeight: "500",
			color: theme.text,
		},
		categoryChipTextActive: {
			color: "#FFFFFF",
			fontWeight: "600",
		},
		exerciseResultsHeader: {
			paddingHorizontal: 20,
			paddingVertical: 16,
		},
		exerciseResultsCount: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.textMuted,
			textTransform: "uppercase",
			letterSpacing: 0.5,
		},
		exerciseCard: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 16,
			gap: 14,
		},
		exerciseCardIcon: {
			width: 52,
			height: 52,
			borderRadius: 14,
			alignItems: "center",
			justifyContent: "center",
		},
		exerciseCardContent: {
			flex: 1,
		},
		exerciseCardHeader: {
			flexDirection: "row",
			alignItems: "center",
			gap: 8,
			marginBottom: 6,
		},
		exerciseCardName: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.text,
			flex: 1,
		},
		exerciseCustomTag: {
			backgroundColor: theme.primary + "20",
			paddingHorizontal: 8,
			paddingVertical: 3,
			borderRadius: 8,
		},
		exerciseCustomTagText: {
			fontSize: 10,
			fontWeight: "700",
			color: theme.primary,
			textTransform: "uppercase",
		},
		exerciseCardMuscles: {
			flexDirection: "row",
			alignItems: "center",
			gap: 6,
			marginBottom: 8,
		},
		exerciseMuscleTag: {
			backgroundColor: theme.background,
			paddingHorizontal: 8,
			paddingVertical: 4,
			borderRadius: 6,
		},
		exerciseMuscleTagText: {
			fontSize: 11,
			fontWeight: "500",
			color: theme.textMuted,
			textTransform: "capitalize",
		},
		exerciseMoreMuscles: {
			fontSize: 11,
			fontWeight: "600",
			color: theme.primary,
		},
		exerciseCardFooter: {
			flexDirection: "row",
			alignItems: "center",
			gap: 12,
		},
		exerciseCardMeta: {
			flexDirection: "row",
			alignItems: "center",
			gap: 6,
		},
		exerciseDifficultyDot: {
			width: 8,
			height: 8,
			borderRadius: 4,
		},
		exerciseDifficultyLabel: {
			fontSize: 12,
			fontWeight: "500",
			color: theme.textMuted,
			textTransform: "capitalize",
		},
		exerciseEquipment: {
			flexDirection: "row",
			alignItems: "center",
			gap: 4,
		},
		exerciseEquipmentText: {
			fontSize: 12,
			fontWeight: "500",
			color: theme.textMuted,
			textTransform: "capitalize",
		},
		exerciseListContent: {
			paddingHorizontal: 16,
			paddingBottom: 24,
		},
		exerciseEmptyState: {
			alignItems: "center",
			paddingVertical: 60,
			paddingHorizontal: 40,
		},
		exerciseEmptyIcon: {
			width: 80,
			height: 80,
			borderRadius: 40,
			backgroundColor: theme.surface,
			alignItems: "center",
			justifyContent: "center",
			marginBottom: 20,
		},
		exerciseEmptyTitle: {
			fontSize: 18,
			fontWeight: "700",
			color: theme.text,
			marginBottom: 8,
		},
		exerciseEmptySubtitle: {
			fontSize: 14,
			color: theme.textMuted,
			textAlign: "center",
			marginBottom: 24,
		},
		exerciseEmptyButton: {
			backgroundColor: theme.primary,
			paddingHorizontal: 24,
			paddingVertical: 12,
			borderRadius: 12,
		},
		exerciseEmptyButtonText: {
			fontSize: 15,
			fontWeight: "600",
			color: "#FFFFFF",
		},
		// Create Exercise Form styles
		createExerciseForm: {
			flex: 1,
			padding: 16,
		},
		formGroup: {
			marginBottom: 24,
		},
		formLabel: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
			marginBottom: 8,
		},
		formInput: {
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 16,
			fontSize: 16,
			color: theme.text,
		},
		formInputMultiline: {
			minHeight: 100,
			textAlignVertical: "top",
		},
		muscleSelector: {
			flexDirection: "row",
			flexWrap: "wrap",
			gap: 8,
		},
		muscleSelectorChip: {
			paddingHorizontal: 14,
			paddingVertical: 8,
			borderRadius: 20,
			backgroundColor: theme.surface,
		},
		muscleSelectorChipActive: {
			backgroundColor: theme.primary,
		},
		muscleSelectorText: {
			fontSize: 13,
			color: theme.text,
		},
		muscleSelectorTextActive: {
			color: "#FFFFFF",
			fontWeight: "600",
		},
		// Category Selector
		categorySelector: {
			flexDirection: "row",
			flexWrap: "wrap",
			gap: 8,
		},
		categorySelectorChip: {
			paddingHorizontal: 14,
			paddingVertical: 8,
			borderRadius: 20,
			backgroundColor: theme.surface,
		},
		categorySelectorChipActive: {
			backgroundColor: theme.primary,
		},
		categorySelectorText: {
			fontSize: 13,
			color: theme.text,
		},
		categorySelectorTextActive: {
			color: "#FFFFFF",
			fontWeight: "600",
		},
		// Rest Timer styles
		timerOverlay: {
			flex: 1,
			backgroundColor: "rgba(0,0,0,0.6)",
			justifyContent: "center",
			alignItems: "center",
		},
		timerModal: {
			width: "88%",
			maxWidth: 420,
			backgroundColor: theme.background,
			borderRadius: 24,
			padding: 24,
		},
		timerDisplay: {
			alignItems: "center",
			marginVertical: 32,
		},
		timerText: {
			fontSize: 64,
			fontWeight: "700",
			color: theme.text,
			fontVariant: ["tabular-nums"],
		},
		timerLabel: {
			fontSize: 14,
			color: theme.textMuted,
			marginTop: 8,
		},
		presetTimes: {
			flexDirection: "row",
			justifyContent: "center",
			gap: 12,
			marginBottom: 24,
		},
		presetButton: {
			paddingHorizontal: 16,
			paddingVertical: 10,
			borderRadius: 12,
			backgroundColor: theme.surface,
		},
		presetButtonActive: {
			backgroundColor: theme.primary + "30",
		},
		presetText: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
		},
		presetTextActive: {
			color: theme.primary,
		},
		timerControls: {
			alignItems: "center",
		},
		startTimerButton: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			backgroundColor: theme.primary,
			paddingVertical: 16,
			paddingHorizontal: 48,
			borderRadius: 16,
			gap: 8,
		},
		startTimerText: {
			fontSize: 18,
			fontWeight: "700",
			color: "#FFFFFF",
			flexShrink: 0,
		},
		// Weight Logger styles
		weightInputSection: {
			padding: 24,
		},
		weightInputRow: {
			flexDirection: "row",
			alignItems: "center",
			gap: 16,
			marginBottom: 24,
		},
		weightInput: {
			flex: 1,
			fontSize: 48,
			fontWeight: "700",
			color: theme.text,
			textAlign: "center",
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 16,
		},
		unitToggle: {
			flexDirection: "column",
			backgroundColor: theme.surface,
			borderRadius: 12,
			overflow: "hidden",
		},
		unitButton: {
			paddingHorizontal: 20,
			paddingVertical: 12,
		},
		unitButtonActive: {
			backgroundColor: theme.primary,
		},
		unitText: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.text,
			flexShrink: 0,
		},
		unitTextActive: {
			color: "#FFFFFF",
		},
		saveWeightButton: {
			backgroundColor: theme.primary,
			paddingVertical: 16,
			borderRadius: 12,
			alignItems: "center",
		},
		saveWeightText: {
			fontSize: 16,
			fontWeight: "700",
			color: "#FFFFFF",
			flexShrink: 0,
		},
		recentWeightsSection: {
			padding: 24,
			paddingTop: 0,
		},
		recentWeightsTitle: {
			fontSize: 18,
			fontWeight: "700",
			color: theme.text,
			marginBottom: 16,
		},
		emptyWeights: {
			alignItems: "center",
			paddingVertical: 32,
		},
		emptyWeightsText: {
			fontSize: 14,
			color: theme.textMuted,
			marginTop: 12,
		},
		weightEntry: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			backgroundColor: theme.surface,
			padding: 16,
			borderRadius: 12,
			marginBottom: 8,
		},
		weightEntryDate: {
			fontSize: 14,
			color: theme.textMuted,
		},
		weightEntryValue: {
			fontSize: 18,
			fontWeight: "700",
			color: theme.text,
		},
	});
