import { Theme } from "@/src/context/themeContext";
import { StyleSheet } from "react-native";

export const createStyles = (theme: Theme) =>
	StyleSheet.create({
		container: {
			flex: 1,
			paddingHorizontal: 16,
		},
		createButton: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 16,
			marginBottom: 16,
		},
		createIconContainer: {
			width: 44,
			height: 44,
			borderRadius: 12,
			backgroundColor: theme.primary,
			justifyContent: "center",
			alignItems: "center",
			marginRight: 12,
		},
		createTextContainer: {
			flex: 1,
		},
		createTitle: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
		},
		createSubtitle: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 2,
		},
		activePlanBanner: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.warning + "20",
			borderRadius: 10,
			paddingVertical: 8,
			paddingHorizontal: 12,
			marginBottom: 16,
		},
		activePlanIcon: {
			marginRight: 8,
		},
		activePlanText: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.warning,
		},
		sectionTitle: {
			fontSize: 16,
			fontWeight: "700",
			color: theme.text,
			marginBottom: 12,
		},
		emptyState: {
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 32,
			alignItems: "center",
		},
		emptyIcon: {
			width: 64,
			height: 64,
			borderRadius: 32,
			backgroundColor: theme.surfaceLight,
			justifyContent: "center",
			alignItems: "center",
			marginBottom: 12,
		},
		emptyTitle: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.text,
		},
		emptySubtitle: {
			fontSize: 13,
			color: theme.textMuted,
			marginTop: 4,
			textAlign: "center",
		},
		planCard: {
			backgroundColor: theme.surface,
			borderRadius: 16,
			padding: 16,
			marginBottom: 12,
		},
		planCardActive: {
			borderWidth: 2,
			borderColor: theme.primary,
		},
		planHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "flex-start",
			marginBottom: 8,
		},
		planTitleRow: {
			flexDirection: "row",
			alignItems: "center",
			gap: 8,
		},
		planName: {
			fontSize: 16,
			fontWeight: "700",
			color: theme.text,
		},
		activeBadge: {
			backgroundColor: theme.primary,
			paddingHorizontal: 8,
			paddingVertical: 2,
			borderRadius: 6,
		},
		activeBadgeText: {
			fontSize: 10,
			fontWeight: "600",
			color: "#FFFFFF",
		},
		planActions: {
			flexDirection: "row",
			gap: 8,
		},
		actionButton: {
			padding: 4,
		},
		planDescription: {
			fontSize: 13,
			color: theme.textMuted,
			marginBottom: 12,
		},
		planMeta: {
			flexDirection: "row",
			gap: 16,
			marginBottom: 12,
		},
		metaItem: {
			flexDirection: "row",
			alignItems: "center",
			gap: 4,
		},
		metaText: {
			fontSize: 12,
			color: theme.textMuted,
		},
		muscleChips: {
			flexDirection: "row",
			flexWrap: "wrap",
			gap: 6,
			marginBottom: 12,
		},
		muscleChip: {
			flexDirection: "row",
			alignItems: "center",
			paddingHorizontal: 8,
			paddingVertical: 4,
			borderRadius: 6,
			gap: 4,
		},
		muscleChipDot: {
			width: 6,
			height: 6,
			borderRadius: 3,
		},
		muscleChipText: {
			fontSize: 11,
			fontWeight: "500",
			color: theme.text,
		},
		planFooter: {
			flexDirection: "row",
			gap: 8,
		},
		setActiveButton: {
			flex: 1,
			paddingVertical: 10,
			borderRadius: 10,
			backgroundColor: theme.surfaceLight,
			alignItems: "center",
		},
		setActiveButtonDisabled: {
			backgroundColor: theme.border,
		},
		setActiveButtonText: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.text,
		},
		setActiveButtonTextActive: {
			color: theme.textMuted,
		},
		startWorkoutButton: {
			flex: 1,
			flexDirection: "row",
			paddingVertical: 10,
			borderRadius: 10,
			backgroundColor: theme.primary,
			alignItems: "center",
			justifyContent: "center",
			gap: 6,
		},
		startWorkoutButtonText: {
			fontSize: 13,
			fontWeight: "600",
			color: "#FFFFFF",
		},
		// Plan Editor Modal Overlay
		planEditorOverlay: {
			flex: 1,
			backgroundColor: "rgba(0,0,0,0.5)",
		},
		// Modal Styles
		modalOverlay: {
			flex: 1,
			backgroundColor: "rgba(0,0,0,0.5)",
			justifyContent: "flex-end",
		},
		modalContent: {
			backgroundColor: theme.background,
			borderTopLeftRadius: 24,
			borderTopRightRadius: 24,
			height: "95%",
			paddingBottom: 30,
		},
		modalHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			padding: 16,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
		},
		modalTitle: {
			fontSize: 17,
			fontWeight: "700",
			color: theme.text,
		},
		modalAction: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.primary,
		},
		stepIndicator: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			paddingVertical: 16,
		},
		stepDot: {
			width: 10,
			height: 10,
			borderRadius: 5,
			backgroundColor: theme.border,
		},
		stepDotActive: {
			backgroundColor: theme.primary,
		},
		stepLine: {
			width: 40,
			height: 2,
			backgroundColor: theme.border,
			marginHorizontal: 8,
		},
		stepContent: {
			padding: 16,
			flex: 1,
		},
		inputGroup: {
			marginBottom: 16,
		},
		inputLabel: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.textSecondary,
			marginBottom: 8,
		},
		textInput: {
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 14,
			fontSize: 15,
			color: theme.text,
		},
		textArea: {
			height: 80,
			textAlignVertical: "top",
		},
		templateGrid: {
			flexDirection: "row",
			flexWrap: "wrap",
			gap: 8,
		},
		templateCard: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			paddingVertical: 10,
			paddingHorizontal: 14,
			borderRadius: 10,
			gap: 6,
		},
		templateCardActive: {
			backgroundColor: theme.primary,
		},
		templateText: {
			fontSize: 12,
			fontWeight: "500",
			color: theme.text,
		},
		templateTextActive: {
			color: "#FFFFFF",
		},
		templateNote: {
			fontSize: 12,
			lineHeight: 17,
			color: theme.textMuted,
			marginBottom: 10,
		},
		selectedSection: {
			marginBottom: 12,
		},
		selectedTitle: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.textSecondary,
			marginBottom: 8,
		},
		selectedScroll: {
			flexGrow: 0,
		},
		selectedChip: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.primary + "20",
			paddingVertical: 6,
			paddingLeft: 10,
			paddingRight: 6,
			borderRadius: 8,
			marginRight: 8,
			gap: 6,
		},
		selectedChipText: {
			fontSize: 12,
			fontWeight: "500",
			color: theme.primary,
		},
		setsControl: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 6,
			paddingHorizontal: 4,
			gap: 4,
		},
		setsText: {
			fontSize: 12,
			fontWeight: "600",
			color: theme.text,
			minWidth: 16,
			textAlign: "center",
		},
		removeExercise: {
			width: 18,
			height: 18,
			borderRadius: 9,
			backgroundColor: theme.error,
			justifyContent: "center",
			alignItems: "center",
		},
		searchContainer: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 10,
			paddingHorizontal: 12,
			marginBottom: 12,
		},
		searchInput: {
			flex: 1,
			paddingVertical: 10,
			paddingLeft: 8,
			fontSize: 14,
			color: theme.text,
		},
		filterScroll: {
			flexGrow: 0,
			marginBottom: 12,
		},
		filterChip: {
			paddingVertical: 6,
			paddingHorizontal: 12,
			borderRadius: 8,
			backgroundColor: theme.surface,
			marginRight: 8,
		},
		filterChipActive: {
			backgroundColor: theme.primary,
		},
		filterChipText: {
			fontSize: 12,
			fontWeight: "500",
			color: theme.text,
		},
		filterChipTextActive: {
			color: "#FFFFFF",
		},
		suggestToggle: {
			flexDirection: "row",
			alignItems: "center",
			alignSelf: "flex-start",
			gap: 6,
			paddingHorizontal: 12,
			paddingVertical: 8,
			borderRadius: 20,
			borderWidth: 1,
			borderColor: theme.primary,
			marginBottom: 10,
		},
		suggestToggleActive: {
			backgroundColor: theme.primary,
		},
		suggestToggleText: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.primary,
		},
		suggestToggleTextActive: {
			color: "#FFF",
		},
		suggestRow: {
			flexDirection: "row",
			alignItems: "flex-start",
			gap: 8,
		},
		aiPlanButton: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			gap: 6,
			paddingHorizontal: 14,
			paddingVertical: 8,
			borderRadius: 20,
			backgroundColor: theme.primary,
			marginBottom: 10,
			minWidth: 120,
		},
		aiPlanButtonText: {
			fontSize: 13,
			fontWeight: "600",
			color: "#FFF",
		},
		injuryFlag: {
			flexDirection: "row",
			alignItems: "center",
			gap: 4,
			marginTop: 4,
		},
		injuryFlagText: {
			fontSize: 11,
			color: theme.warning,
			flexShrink: 1,
		},
		exerciseList: {
			flex: 1,
		},
		exerciseItem: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.surface,
			borderRadius: 12,
			padding: 12,
			marginBottom: 8,
		},
		exerciseItemSelected: {
			backgroundColor: theme.primary + "20",
			borderWidth: 1,
			borderColor: theme.primary,
		},
		exerciseInfo: {
			flex: 1,
		},
		exerciseInfoButton: {
			paddingHorizontal: 10,
		},
		exerciseName: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.text,
			marginBottom: 4,
		},
		exerciseMuscles: {
			flexDirection: "row",
			gap: 8,
		},
		exerciseMuscle: {
			fontSize: 11,
			color: theme.textMuted,
		},
		exerciseCheck: {
			width: 22,
			height: 22,
			borderRadius: 11,
			borderWidth: 2,
			borderColor: theme.border,
			justifyContent: "center",
			alignItems: "center",
		},
		exerciseCheckSelected: {
			backgroundColor: theme.primary,
			borderColor: theme.primary,
		},
		// Editor styles
		editorContainer: {
			flex: 1,
			backgroundColor: theme.background,
			marginTop: 50,
			borderTopLeftRadius: 24,
			borderTopRightRadius: 24,
			overflow: "hidden",
		},
		editorHeader: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			paddingHorizontal: 16,
			paddingVertical: 12,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
			backgroundColor: theme.surface,
		},
		editorBackBtn: {
			padding: 4,
		},
		editorTitle: {
			fontSize: 17,
			fontWeight: "600",
			color: theme.text,
		},
		editorSaveBtn: {
			paddingVertical: 6,
			paddingHorizontal: 12,
			backgroundColor: theme.primary,
			borderRadius: 8,
		},
		editorSaveText: {
			fontSize: 14,
			fontWeight: "600",
			color: "#FFFFFF",
		},
		editorContent: {
			flex: 1,
			paddingHorizontal: 16,
		},
		editorSection: {
			marginTop: 16,
		},
		editorSectionTitle: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.textSecondary,
			marginBottom: 12,
		},
		editorPlanName: {
			fontSize: 20,
			fontWeight: "700",
			color: theme.text,
			paddingVertical: 12,
			borderBottomWidth: 1,
			borderBottomColor: theme.border,
		},
		editorDescription: {
			fontSize: 14,
			color: theme.textMuted,
			paddingVertical: 12,
			minHeight: 60,
		},
		exerciseCard: {
			backgroundColor: theme.surface,
			borderRadius: 12,
			marginBottom: 12,
			overflow: "hidden",
		},
		exerciseCardHeader: {
			flexDirection: "row",
			alignItems: "center",
			padding: 14,
		},
		reorderButtons: {
			flexDirection: "column",
			marginRight: 8,
		},
		reorderBtn: {
			padding: 2,
		},
		reorderBtnDisabled: {
			opacity: 0.3,
		},
		exerciseCardInfoTouch: {
			flex: 1,
			flexDirection: "row",
			alignItems: "center",
		},
		exerciseOrderBadge: {
			width: 28,
			height: 28,
			borderRadius: 14,
			backgroundColor: theme.primary + "20",
			justifyContent: "center",
			alignItems: "center",
			marginRight: 12,
		},
		exerciseOrderText: {
			fontSize: 13,
			fontWeight: "700",
			color: theme.primary,
		},
		exerciseCardInfo: {
			flex: 1,
		},
		exerciseCardName: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.text,
		},
		exerciseCardMuscles: {
			fontSize: 12,
			color: theme.textMuted,
			marginTop: 2,
		},
		exerciseCardActions: {
			flexDirection: "row",
			alignItems: "center",
			gap: 8,
		},
		exerciseSetsCount: {
			fontSize: 12,
			color: theme.textMuted,
			fontWeight: "500",
		},
		exerciseCardBody: {
			paddingHorizontal: 14,
			paddingBottom: 14,
			borderTopWidth: 1,
			borderTopColor: theme.border,
		},
		setsHeader: {
			flexDirection: "row",
			alignItems: "center",
			paddingVertical: 10,
			gap: 12,
		},
		setsHeaderText: {
			fontSize: 11,
			fontWeight: "600",
			color: theme.textMuted,
			textTransform: "uppercase",
			flex: 1,
			textAlign: "center",
		},
		setRow: {
			flexDirection: "row",
			alignItems: "center",
			marginBottom: 8,
			gap: 12,
		},
		setNumberBadge: {
			width: 28,
			height: 28,
			borderRadius: 14,
			backgroundColor: theme.surfaceLight,
			justifyContent: "center",
			alignItems: "center",
			flex: 1,
		},
		setNumberText: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.text,
		},
		setInput: {
			flex: 1,
			backgroundColor: theme.surfaceLight,
			borderRadius: 8,
			paddingHorizontal: 12,
			paddingVertical: 8,
			fontSize: 14,
			fontWeight: "500",
			color: theme.text,
			textAlign: "center",
		},
		removeSetBtn: {
			padding: 4,
		},
		exerciseCardFooter: {
			flexDirection: "row",
			justifyContent: "space-between",
			marginTop: 8,
			paddingTop: 8,
			borderTopWidth: 1,
			borderTopColor: theme.border,
		},
		addSetBtn: {
			flexDirection: "row",
			alignItems: "center",
			gap: 4,
		},
		addSetText: {
			fontSize: 13,
			fontWeight: "500",
			color: theme.primary,
		},
		removeExerciseBtn: {
			flexDirection: "row",
			alignItems: "center",
			gap: 4,
		},
		removeExerciseText: {
			fontSize: 13,
			fontWeight: "500",
			color: theme.error,
		},
		addExerciseBtn: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			gap: 8,
			padding: 16,
			borderRadius: 12,
			borderWidth: 2,
			borderStyle: "dashed",
			borderColor: theme.border,
		},
		addExerciseText: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.primary,
		},
	});
