import { Alert } from "@/src/components/CustomAlert";
import { Theme, useColors } from "@/src/context/themeContext";
import Ionicons from "@expo/vector-icons/Ionicons";
import React, { useMemo, useState } from "react";
import { Image, ImageSourcePropType, Platform, StyleSheet, Text, TouchableOpacity, View } from "react-native";

/**
 * Launcher icon variants. `name` must match an expo-alternate-app-icons entry
 * in app.json (null = the default icon); the images are generated by
 * scripts/generate-icons.py.
 */
const ICON_VARIANTS: { name: string | null; label: string; preview: ImageSourcePropType }[] = [
	{ name: null, label: "Midnight", preview: require("@/assets/images/icon.png") },
	{ name: "Light", label: "Light", preview: require("@/assets/images/app-icons/light.png") },
	{ name: "Black", label: "Black", preview: require("@/assets/images/app-icons/black.png") },
	{ name: "Ocean", label: "Ocean", preview: require("@/assets/images/app-icons/ocean.png") },
];

// The native module only exists in builds made after the library was added;
// an older dev build would crash on import, so load it lazily.
type IconModule = typeof import("expo-alternate-app-icons");
let iconModule: IconModule | null | undefined;
function getIconModule(): IconModule | null {
	if (iconModule === undefined) {
		try {
			iconModule = require("expo-alternate-app-icons") as IconModule;
		} catch {
			iconModule = null;
		}
	}
	return iconModule;
}

/** Settings > Appearance > App icon: lets the user switch the launcher icon. */
export function AppIconPicker() {
	const theme = useColors();
	const s = useMemo(() => createStyles(theme), [theme]);
	const mod = getIconModule();
	const supported = !!mod?.supportsAlternateIcons;
	const [current, setCurrent] = useState<string | null>(() => {
		try {
			return mod?.getAppIconName() ?? null;
		} catch {
			return null;
		}
	});

	if (!supported) return null;

	const choose = async (name: string | null) => {
		if (name === current) return;
		try {
			await mod!.setAlternateAppIcon(name);
			setCurrent(name);
			if (Platform.OS === "android") {
				Alert.success(
					"App icon changed",
					"Your launcher may take a few seconds to show the new icon, and LifeSync might close once while it switches.",
				);
			}
		} catch {
			Alert.error("Couldn't change the icon", "Please try again.");
		}
	};

	return (
		<View style={s.wrap}>
			<View style={s.header}>
				<View style={[s.iconBox, { backgroundColor: theme.primary + "20" }]}>
					<Ionicons name="apps" size={20} color={theme.primary} />
				</View>
				<View style={{ flex: 1 }}>
					<Text style={s.label}>App icon</Text>
					<Text style={s.description}>Choose how LifeSync looks on your home screen</Text>
				</View>
			</View>
			<View style={s.row}>
				{ICON_VARIANTS.map((v) => {
					const selected = v.name === current;
					return (
						<TouchableOpacity key={v.label} style={s.option} onPress={() => choose(v.name)} activeOpacity={0.7}>
							<View style={[s.previewRing, selected && { borderColor: theme.primary }]}>
								<Image source={v.preview} style={s.preview} />
							</View>
							<Text style={[s.optionLabel, selected && { color: theme.primary, fontWeight: "700" }]}>
								{v.label}
							</Text>
						</TouchableOpacity>
					);
				})}
			</View>
		</View>
	);
}

const createStyles = (theme: Theme) =>
	StyleSheet.create({
		wrap: { paddingHorizontal: 16, paddingVertical: 14, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.border },
		header: { flexDirection: "row", alignItems: "center", gap: 12 },
		iconBox: { width: 36, height: 36, borderRadius: 10, alignItems: "center", justifyContent: "center" },
		label: { fontSize: 15, fontWeight: "600", color: theme.text },
		description: { fontSize: 12, color: theme.textSecondary, marginTop: 2 },
		row: { flexDirection: "row", justifyContent: "space-between", marginTop: 14 },
		option: { alignItems: "center", gap: 6, flex: 1 },
		previewRing: { padding: 3, borderRadius: 20, borderWidth: 2, borderColor: "transparent" },
		preview: { width: 56, height: 56, borderRadius: 15 },
		optionLabel: { fontSize: 12, color: theme.textSecondary },
	});
