// AUTO-GENERATED by scripts/fetch-exercise-videos.mjs - do not edit by hand.
// Put hand-picked replacements in OVERRIDES in that script and re-run it.
// Videos are embedded with YouTube's player; they remain the creators' content.

export const EXERCISE_VIDEOS: Record<string, string> = {
	// How To: Barbell Bench Press — ScottHermanFitness
	ex_bench_press: "rT7DgCr-3pg",
	// How To: Dumbbell Incline Press | 3 GOLDEN RULES (MADE BETTER!) — ScottHermanFitness
	ex_incline_bench: "hChjZQhX1Ls",
	// How to Properly Do a DUMBBELL FLY | Mind Pump — Mind Pump TV
	ex_dumbbell_flyes: "QENKPHhQVi4",
	// Do Push-Ups with Proper Form! — Upright Health
	ex_pushups: "I9fsqKE5XHo",
	// STOP F*cking Up Cable Flys (PROPER FORM!) — ATHLEAN-X™
	ex_cable_crossover: "JUDTGZh4rhg",
	// How to PROPERLY Deadlift for Growth (5 Easy Steps) — Jeremy Ethier
	ex_deadlift: "XxWcirHIwVo",
	// The Best Way To Do Pull Ups For A Wide Back (Optimal Training Technique) — Jeff Nippard
	ex_pullups: "Hdc7Mw6BIEE",
	// How To PROPERLY Barbell Row For A Bigger Back (Stop Making These Mistakes!) — Jeremy Ethier
	ex_barbell_row: "kBWAon7ItDw",
	// How to do Lat Pulldowns (AVOID MISTAKES!) — ATHLEAN-X™
	ex_lat_pulldown: "SALxEARiMkw",
	// How To Properly Do The Seated Cable Row (IT MATTERS!) — Mind Pump TV
	ex_seated_row: "sP_4vybjVJs",
	// Build Bigger Shoulders With Perfect Training Technique (The Overhead Press) — Jeff Nippard
	ex_overhead_press: "_RlRDWO2jfg",
	// How To: Dumbbell Side Lateral Raise — ScottHermanFitness
	ex_lateral_raises: "3VcKaXpzqRo",
	// STOP F*cking Up Face Pulls (PROPER FORM!) — ATHLEAN-X™
	ex_face_pulls: "ljgqer1ZpXg",
	// How To: Barbell Bicep Curl | 3 GOLDEN RULES — ScottHermanFitness
	ex_barbell_curl: "QZEqB6wUPxQ",
	// HOW TO: Dumbbell Hammer Curl (BICEPS PEAK BUILDER!) || PERFECT FORM — ScottHermanFitness
	ex_hammer_curl: "8XLxfXROrTo",
	// HOW TO: Cable Triceps Pushdown || 3 Golden Rules (FOR GROWTH) — ScottHermanFitness
	ex_tricep_pushdown: "_w-HpW70nSQ",
	// How To: Skull Crusher (BUILD BIGGER TRICEPS!) || PERFECT FORM — ScottHermanFitness
	ex_skull_crushers: "RavQHfFxbdA",
	// How to PROPERLY Squat for Growth (4 Easy Steps) — Jeremy Ethier
	ex_barbell_squat: "gcNh17Ckjgg",
	// How To Leg Press For Best Quad Growth | Targeting The Muscle Series — Renaissance Periodization
	ex_leg_press: "B6rGDcfyPto",
	// Walking Lunges Exercise Tutorial | Build Legendary Legs & Cardio — Buff Dudes Workouts
	ex_lunges: "Pbmj6xPo-Hw",
	// HOW TO DO ROMANIAN DEADLIFTS (RDLs): Build Beefy Hamstrings With Perfect Technique — Jeff Nippard
	ex_romanian_deadlift: "_oyxCn2iSjU",
	// Beginner's Guide: Seated Leg Curl — SilverSneakers
	ex_leg_curl: "t9sTSr-JYSs",
	// How To Do Leg Extensions With Perfect Technique (Grow Every Quad Head) — Jeff Nippard
	ex_leg_extension: "ljO4jkwv8wQ",
	// How To: Standing Barbell Calf Raise — ScottHermanFitness
	ex_calf_raises: "3UWi44yN-wM",
	// How To Plank (Proper Form | Cues | Progressions) — E3 Rehab
	ex_plank: "A2b2EmIg0dA",
	// How To Do Crunches | The Right Way | Well+Good — Well+Good
	ex_crunches: "0t4t3IpiEao",
	// How to Do a Russian Twist | Ab Workout — Howcast
	ex_russian_twist: "wkD8rjkodUI",
	// Hanging Leg Raise | HOW-TO — ATHLEAN-X™
	ex_hanging_leg_raise: "Pr1ieGZ5atk",
	// What Is Perfect Running Form? (Tips for All Runners) — Nicklas Rossner
	ex_running: "u5EMsxkfswA",
	// How To Pedal | Cycling Technique — Global Cycling Network
	ex_cycling: "hPcR6MQ5dJo",
	// Correct Rowing Machine Technique, Improve Your Rowing  | Concept2 — concept2usa
	ex_rowing: "4zWu1yuJ0_g",
	// How To Jump Rope | The Right Way | Well+Good — Well+Good
	ex_jump_rope: "u3zgHI8QnqE",
	// How To Do A Burpee | The Right Way | Well+Good — Well+Good
	ex_burpees: "qLBImHhCXSw",
	// How To Do A Downward Dog | The Right Way | Well+Good — Well+Good
	ex_downward_dog: "05Mqw_ss2qg",
	// Warrior I (Virabhadrasana I) - Yoga Pose Tutorial by Muscle and Motion — Muscle & Motion
	ex_warrior_one: "fniJmxMyqBU",
	// Warrior II: (Virabhadrasana II) - Yoga Pose Guide Tutorial — YogaDownload
	ex_warrior_two: "4zLhHe99v0o",
	// How to Do a Tree Pose (Vrksasana) | Yoga — Howcast
	ex_tree_pose: "wdln9qWYloU",
	// Beginners Yoga: How to do Balasana - Child's Pose — Yoga & You
	ex_childs_pose: "2MJGg-dUKh0",
	// How to Do the Cobra Pose — Howcast
	ex_cobra_pose: "zgvolE4NAH0",
	// How to Do a Cat Cow Stretch: A Guide from Physical Therapists — Hinge Health
	ex_cat_cow: "1Y0YjXS9sKI",
	// How To Do Pigeon Pose | The Right Way | Well+Good — Well+Good
	ex_pigeon_pose: "M1gEGLtF1p0",
	// How to do Paschimottanasana? Forward Bending Yoga Pose | How to Touch Your Toes |Seated Forward Bend — The Yoga Institute
	ex_seated_forward_fold: "E5FtZEVC424",
	// How To Do BRIDGE POSE | Step By Step SETU BANDHASANA | Simple Yoga Lessons | Yoga For Beginners — Mind Body Soul
	ex_bridge_pose: "EZyBkVBUlG4",
	// How To Do Triangle Pose | The Right Way | Well+Good — Well+Good
	ex_triangle_pose: "_1124fj0BeQ",
	// How To Perform Surya Namaskar for Beginners I Sun Salutations I Step-by-Step Guide |12 Easy Steps — The Yoga Institute
	ex_sun_salutation: "_2GgRQJ9IbU",
	// How to Do a Corpse Pose (Savasana) | Yoga — Howcast
	ex_corpse_pose: "ocnRmfbFV9E",
	// How to do High Knees | Forever Living UK & Ireland — Forever Living Products UK 
	ex_high_knees: "FvjmPRU3zn4",
	// How to do Jumping Jacks exercise - Best Cardio Exercises video tutorial — P4P WORKOUTS 
	ex_jumping_jacks: "XR0xeuK5zBU",
	// How to Do Mountain Climbers | The Right Way | Well+Good — Well+Good
	ex_mountain_climbers: "cnyTQDSE884",
	// How To: Box Jump — ScottHermanFitness
	ex_box_jumps: "hxldG9FX4j4",
	// Stair climbing Muscles: What they are and How to train them — Therani
	ex_stair_climbing: "sCPAaFc38zc",
	// How to Use Battle Ropes The RIGHT Way (Try These!) — Mind Pump TV
	ex_battle_ropes: "nzlmTiKqno0",
	// Elliptical Instruction 101: Technique and Tips — Sunny Health & Fitness
	ex_elliptical: "YWfswVvOaiI",
	// How To Swim Freestyle | Technique For Front Crawl Swimming — Global Triathlon Network
	ex_swimming: "AQy_c30lNjI",
	// HOW TO DO SKATER JUMPS — Personal Fitness by Clint Neale
	ex_skipping: "BGrTRCjTPFo",
	// Over 55 - Stop Knee & Hip Pain Fast By Walking Properly — Bob & Brad
	ex_walking: "nOw9d7RqU58",
	// Interval Sprints | High Intensity Training - Speed Conditioning — Simple Speed Coach
	ex_sprint_intervals: "Ky_1tRwadCs",
	// Mckenzie Exercises: Lumbar Spine Extension in Prone Lying with Therapist Overpressure James Sharp — James Sharp Physiotherapy
	ex_prone_lying: "qALyVjkSqhg",
	// Prone Press Up on Elbows (Hold) — E3 Rehab Exercise Library
	ex_prone_on_elbows: "ZjgEge1cKwo",
	// Prone Press Ups - Ask Doctor Jo — AskDoctorJo
	ex_prone_press_up: "UqSP7ZrHxRE",
	// Standing Trunk Extension - Ask Doctor Jo — AskDoctorJo
	ex_standing_extension: "p0Us4jY1yNQ",
	// Single Knee to Chest - Ask Doctor Jo — AskDoctorJo
	ex_single_knee_to_chest: "Yd9wY25koVk",
	// Double Knee to Chest - Ask Doctor Jo — AskDoctorJo
	ex_double_knee_to_chest: "5R7eWaNWO3U",
	// How to Do a Supine Posterior Pelvic Tilt Exercise | MedBridge — Medbridge
	ex_pelvic_tilt: "Q59R9p4rzxw",
	// How To Correctly Perform The McGill Modified Curl Up — Ryan Hollien
	ex_mcgill_curl_up: "_tz9WGVH25g",
	// Modified Side Plank Knees Bent — Column Core Human Performance 
	ex_side_plank_modified: "TFjqme8dPX0",
	// How to Do the Bird Dog Exercise: A Guide from Physical Therapists — Hinge Health
	ex_bird_dog: "xEDnlOxeJH4",
	// Dead Bug Exercises — Bob & Brad
	ex_dead_bug: "cnBYCszEoWQ",
	// Nerve Glide - Sciatic - Ask Doctor Jo — AskDoctorJo
	ex_sciatic_nerve_glide_supine: "XP1yzpFR6ho",
	// Nerve Glide - Sciatic - Ask Doctor Jo — AskDoctorJo
	ex_sciatic_nerve_glide_seated: "XP1yzpFR6ho",
	// Piriformis Figure 4 Stretch - Ask Doctor Jo — AskDoctorJo
	ex_piriformis_stretch: "-g0nuyTHMrI",
	// How to Do a Glute Bridge Exercise: A Guide from Physical Therapists — Hinge Health
	ex_glute_bridge: "PhTDzR0TpZs",
	// How to Do the Clamshell Exercise — Hinge Health
	ex_clamshell: "gFyIjunfbbg",
	// Dynamic Half Kneeling Hip Flexor Stretch — E3 Rehab Exercise Library
	ex_kneeling_hip_flexor_stretch: "_HrlhENbT0w",
	// Hamstring Stretch with a Strap, Supine - Ask Doctor Jo — AskDoctorJo
	ex_supine_hamstring_stretch_strap: "Il1L75v6gq0",
	// Stop Low Back Pain With Dr. Stuart McGill’s “Walking Program”, Back Balm — Bob & Brad
	ex_walking_rehab: "II6t-rMLFOI",
	// Tibialis Raise | How to do it and why it is important — CrossFit Federal Hill
	ex_tibialis_raise: "RXC7tE6IQcc",
	// Bent Knee Calf Raise Exercise Tutorial - Proper Form and Technique — Runna
	ex_bent_knee_calf_raise: "NcMjGCO_-J0",
	// How To: Single-Leg Calf Raise — ScottHermanFitness
	ex_single_leg_calf_raise: "ORT4oJ_R8Qs",
	// Eccentric Heel Drop (achilles strengthening and mobility) — Black Bear Physical Therapy 
	ex_eccentric_heel_drop: "3tc0lN_bW5o",
	// How to Set Up, Perform, & Program Copenhagen Planks (Progressions | Regressions | Alternatives) — E3 Rehab
	ex_copenhagen_plank: "YRRnnZsRs9U",
	// The BEST Single-Leg RDL Tutorial (Romanian Deadlift) — Squat University
	ex_single_leg_rdl: "Zfr6wizR8rs",
	// How to do the STEP UP: technique and common mistakes — Get Exercise Confident
	ex_step_up: "WCFCdxzFBa4",
	// How to do Lateral Band Walking — National Academy of Sports Medicine (NASM)
	ex_lateral_band_walk: "M5uxEQH5BUM",
	// How To Do Pogo Hops | Exercise Demonstration Video and Guide — Live Lean TV Daily Exercises
	ex_pogo_hops: "c2LBofIzUqs",
	// The Weight Bearing Lunge Test or Wall Test | Ankle Mobility — Physiotutors
	ex_ankle_knee_to_wall: "U7woPNLUT3Q",
	// How To Do Leg Swings — PureGym
	ex_leg_swings: "difYoBtZi2s",
	// How to Do A-Skip - B-Skip with Proper Form- Find Your Stride with Coach John Smith — Runify
	ex_a_skip: "A7r6yCpmSrA",
	// How to Do a Standing Calf Stretch | Knee Exercises — Howcast
	ex_standing_calf_stretch: "6vEeaK3tvzE",
	// Performing The Short Foot Exercise Properly — CPCinfo
	ex_short_foot: "iy1Qxt2mnsE",
	// Towel Scrunches Exercise for Flat Feet Plantar Fasciitis and Toe strength — The Strong Angle
	ex_towel_scrunch: "1ogSryKJXB4",
	// Foot Care 6: Marble Pick Up — IMG PHYSICAL THERAPY
	ex_marble_pickup: "A1EEvIEfxpo",
	// How to Do a Toe Yoga Exercise: A Guide from Physical Therapists — Hinge Health
	ex_toe_yoga: "QVZpBSVV9js",
	// 26. Toes-spread-out exercise or splaying — Eric Price
	ex_toe_splay: "OG2w7RyGZVg",
	// Heel Raise With Ball Squeeze - For Posterior Tib Activation — Sole Physical Therapy
	ex_heel_raise_ball: "IjoSXiL-dO0",
	// Ankle Inversion with Resistive Band - Ask Doctor Jo — AskDoctorJo
	ex_banded_inversion: "50YDq8_OA_w",
	// Single Leg Balance — E3 Rehab Exercise Library
	ex_single_leg_balance: "nLHy38nxMmY",
	// Plantar Fascia Stretch | Plantar Fasciitis — Physiotutors
	ex_plantar_fascia_stretch: "A6xAC0RGGaQ",
	// Foot Rolling — Dr. Beau Beard
	ex_foot_roll: "6-KYvJanans",
};

export const getExerciseVideo = (exerciseId: string): string | undefined =>
	EXERCISE_VIDEOS[exerciseId];
